export const ligue1Teams = [
  {
    id: 44,
    nom: "Olympique Marseille",
    shortName: "OM",
    slug: "marseille",
    players: [
      {
        id: 186418,
        nom: "Gerónimo Rulli",
        displayName: "Gerónimo Rulli",
        position: "GK",
        position_id: 24,
        numero: 1,
        age: "33",
        nationalite: "Argentina",
        taille: 189,
        poids: 84,
        image: "https://cdn.sportmonks.com/images/soccer/players/18/186418.png",
        playerSlug: "gerónimo-rulli"
      },
      {
        id: 29186,
        nom: "Jeffrey de Lange",
        displayName: "Jeffrey de Lange",
        position: "GK",
        position_id: 24,
        numero: 12,
        age: "27",
        nationalite: "Netherlands",
        taille: 190,
        poids: null,
        image: "https://cdn.sportmonks.com/images/soccer/players/2/29186.png",
        playerSlug: "jeffrey-de-lange"
      },
      {
        id: 186456,
        nom: "Rubén Blanco",
        displayName: "Rubén Blanco",
        position: "GK",
        position_id: 24,
        numero: 36,
        age: "30",
        nationalite: "Spain",
        taille: 188,
        poids: 70,
        image: "https://cdn.sportmonks.com/images/soccer/players/24/186456.png",
        playerSlug: "rubén-blanco"
      },
      {
        id: 37593233,
        nom: "Jelle Van Neck",
        displayName: "Jelle Van Neck",
        position: "GK",
        position_id: 24,
        numero: 40,
        age: "21",
        nationalite: "Belgium",
        taille: 191,
        poids: null,
        image: "https://cdn.sportmonks.com/images/soccer/players/17/37593233.png",
        playerSlug: "jelle-van-neck"
      },
      {
        id: 527759,
        nom: "Théo Vermot",
        displayName: "Théo Vermot",
        position: "GK",
        position_id: 24,
        numero: 92,
        age: "28",
        nationalite: "France",
        taille: null,
        poids: null,
        image: "https://cdn.sportmonks.com/images/soccer/placeholder.png",
        playerSlug: "théo-vermot"
      },
      {
        id: 13171199,
        nom: "Leonardo Balerdi",
        displayName: "Leonardo Balerdi",
        position: "DF",
        position_id: 25,
        numero: 5,
        age: "26",
        nationalite: "Argentina",
        taille: 187,
        poids: 85,
        image: "https://cdn.sportmonks.com/images/soccer/players/31/13171199.png",
        playerSlug: "leonardo-balerdi"
      },
      {
        id: 32390,
        nom: "Ulisses Garcia",
        displayName: "Ulisses Garcia",
        position: "DF",
        position_id: 25,
        numero: 6,
        age: "29",
        nationalite: "Switzerland",
        taille: 182,
        poids: 78,
        image: "https://cdn.sportmonks.com/images/soccer/players/6/32390.png",
        playerSlug: "ulisses-garcia"
      },
      {
        id: 586846,
        nom: "Derek Cornelius",
        displayName: "Derek Cornelius",
        position: "DF",
        position_id: 25,
        numero: 13,
        age: "27",
        nationalite: "Canada",
        taille: 182,
        poids: 76,
        image: "https://cdn.sportmonks.com/images/soccer/players/30/586846.png",
        playerSlug: "derek-cornelius"
      },
      {
        id: 37369302,
        nom: "Bamo Meïté",
        displayName: "Bamo Meïté",
        position: "DF",
        position_id: 25,
        numero: 18,
        age: "23",
        nationalite: "France",
        taille: 184,
        poids: null,
        image: "https://cdn.sportmonks.com/images/soccer/players/22/37369302.png",
        playerSlug: "bamo-meïté"
      },
      {
        id: 130063,
        nom: "Pol Lirola",
        displayName: "Pol Lirola",
        position: "DF",
        position_id: 25,
        numero: 29,
        age: "28",
        nationalite: "Spain",
        taille: 173,
        poids: 69,
        image: "https://cdn.sportmonks.com/images/soccer/players/15/130063.png",
        playerSlug: "pol-lirola"
      },
      {
        id: 335521,
        nom: "Facundo Medina",
        displayName: "Facundo Medina",
        position: "DF",
        position_id: 25,
        numero: 32,
        age: "26",
        nationalite: "Argentina",
        taille: 184,
        poids: 78,
        image: "https://cdn.sportmonks.com/images/soccer/players/1/335521.png",
        playerSlug: "facundo-medina"
      },
      {
        id: 28575687,
        nom: "CJ Egan-Riley",
        displayName: "CJ Egan-Riley",
        position: "DF",
        position_id: 25,
        numero: 4,
        age: "22",
        nationalite: "England",
        taille: 183,
        poids: null,
        image: "https://cdn.sportmonks.com/images/soccer/players/7/28575687.png",
        playerSlug: "cj-egan-riley"
      },
      {
        id: 512560,
        nom: "Amir Murillo",
        displayName: "Amir Murillo",
        position: "DF",
        position_id: 25,
        numero: 62,
        age: "29",
        nationalite: "Panama",
        taille: 185,
        poids: 79,
        image: "https://cdn.sportmonks.com/images/soccer/players/16/512560.png",
        playerSlug: "amir-murillo"
      },
      {
        id: 1744,
        nom: "Pierre-Emile Højbjerg",
        displayName: "Pierre-Emile Højbjerg",
        position: "MF",
        position_id: 26,
        numero: 23,
        age: "30",
        nationalite: "Denmark",
        taille: 185,
        poids: 84,
        image: "https://cdn.sportmonks.com/images/soccer/players/16/1744.png",
        playerSlug: "pierre-emile-højbjerg"
      },
      {
        id: 21803033,
        nom: "Azzedine Ounahi",
        displayName: "Azzedine Ounahi",
        position: "MF",
        position_id: 26,
        numero: 8,
        age: "25",
        nationalite: "Morocco",
        taille: 182,
        poids: null,
        image: "https://cdn.sportmonks.com/images/soccer/players/25/21803033.png",
        playerSlug: "azzedine-ounahi"
      },
      {
        id: 96691,
        nom: "Amine Harit",
        displayName: "Amine Harit",
        position: "MF",
        position_id: 26,
        numero: 11,
        age: "28",
        nationalite: "Morocco",
        taille: 183,
        poids: 78,
        image: "https://cdn.sportmonks.com/images/soccer/players/19/96691.png",
        playerSlug: "amine-harit"
      },
      {
        id: 95696,
        nom: "Geoffrey Kondogbia",
        displayName: "Geoffrey Kondogbia",
        position: "MF",
        position_id: 26,
        numero: 19,
        age: "32",
        nationalite: "Central African Republic",
        taille: 188,
        poids: 76,
        image: "https://cdn.sportmonks.com/images/soccer/players/16/95696.png",
        playerSlug: "geoffrey-kondogbia"
      },
      {
        id: 95694,
        nom: "Adrien Rabiot",
        displayName: "Adrien Rabiot",
        position: "MF",
        position_id: 26,
        numero: 25,
        age: "30",
        nationalite: "France",
        taille: 191,
        poids: 81,
        image: "https://cdn.sportmonks.com/images/soccer/players/14/95694.png",
        playerSlug: "adrien-rabiot"
      },
      {
        id: 37541144,
        nom: "Bilal Nadir",
        displayName: "Bilal Nadir",
        position: "MF",
        position_id: 26,
        numero: 26,
        age: "21",
        nationalite: "France",
        taille: 175,
        poids: null,
        image: "https://cdn.sportmonks.com/images/soccer/players/24/37541144.png",
        playerSlug: "bilal-nadir"
      },
      {
        id: 608285,
        nom: "Angel Gomes",
        displayName: "Angel Gomes",
        position: "MF",
        position_id: 26,
        numero: 8,
        age: "24",
        nationalite: "England",
        taille: 168,
        poids: 61,
        image: "https://cdn.sportmonks.com/images/soccer/players/29/608285.png",
        playerSlug: "angel-gomes"
      },
      {
        id: 37737405,
        nom: "Darryl Bakola",
        displayName: "Darryl Bakola",
        position: "MF",
        position_id: 26,
        numero: 50,
        age: "17",
        nationalite: "France",
        taille: 178,
        poids: null,
        image: "https://cdn.sportmonks.com/images/soccer/players/29/37737405.png",
        playerSlug: "darryl-bakola"
      },
      {
        id: 433458,
        nom: "Amine Gouiri",
        displayName: "Amine Gouiri",
        position: "FW",
        position_id: 27,
        numero: 9,
        age: "25",
        nationalite: "Algeria",
        taille: 180,
        poids: 72,
        image: "https://cdn.sportmonks.com/images/soccer/players/18/433458.png",
        playerSlug: "amine-gouiri"
      },
      {
        id: 31739,
        nom: "Pierre-Emerick Aubameyang",
        displayName: "Pierre-Emerick Aubameyang",
        position: "FW",
        position_id: 27,
        numero: 97,
        age: "36",
        nationalite: "Gabon",
        taille: 187,
        poids: 80,
        image: "https://cdn.sportmonks.com/images/soccer/players/27/31739.png",
        playerSlug: "pierre-emerick-aubameyang"
      },
      {
        id: 20333643,
        nom: "Mason Greenwood",
        displayName: "Mason Greenwood",
        position: "FW",
        position_id: 27,
        numero: 10,
        age: "23",
        nationalite: "England",
        taille: 181,
        poids: null,
        image: "https://cdn.sportmonks.com/images/soccer/players/11/20333643.png",
        playerSlug: "mason-greenwood"
      },
      {
        id: 95776,
        nom: "Neal Maupay",
        displayName: "Neal Maupay",
        position: "FW",
        position_id: 27,
        numero: 7,
        age: "29",
        nationalite: "France",
        taille: 171,
        poids: 69,
        image: "https://cdn.sportmonks.com/images/soccer/players/0/95776.png",
        playerSlug: "neal-maupay"
      },
      {
        id: 20315925,
        nom: "Faris Moumbagna",
        displayName: "Faris Moumbagna",
        position: "FW",
        position_id: 27,
        numero: 14,
        age: "25",
        nationalite: "Cameroon",
        taille: 185,
        poids: 77,
        image: "https://cdn.sportmonks.com/images/soccer/players/21/20315925.png",
        playerSlug: "faris-moumbagna"
      },
      {
        id: 29328428,
        nom: "Igor Paixão",
        displayName: "Igor Paixão",
        position: "FW",
        position_id: 27,
        numero: 14,
        age: "25",
        nationalite: "Brazil",
        taille: 175,
        poids: null,
        image: "https://cdn.sportmonks.com/images/soccer/players/12/29328428.png",
        playerSlug: "igor-paixão"
      },
      {
        id: 537332,
        nom: "Timothy Weah",
        displayName: "Timothy Weah",
        position: "FW",
        position_id: 27,
        numero: 22,
        age: "25",
        nationalite: "United States",
        taille: 183,
        poids: 73,
        image: "https://cdn.sportmonks.com/images/soccer/players/20/537332.png",
        playerSlug: "timothy-weah"
      },
      {
        id: 37657133,
        nom: "François Mughe",
        displayName: "François Mughe",
        position: "FW",
        position_id: 27,
        numero: 24,
        age: "21",
        nationalite: "Cameroon",
        taille: 173,
        poids: null,
        image: "https://cdn.sportmonks.com/images/soccer/players/13/37657133.png",
        playerSlug: "françois-mughe"
      },
      {
        id: 34455209,
        nom: "Jonathan Rowe",
        displayName: "Jonathan Rowe",
        position: "FW",
        position_id: 27,
        numero: 17,
        age: "22",
        nationalite: "England",
        taille: 174,
        poids: 60,
        image: "https://cdn.sportmonks.com/images/soccer/players/9/34455209.png",
        playerSlug: "jonathan-rowe"
      },
      {
        id: 37713942,
        nom: "Robinio Vaz",
        displayName: "Robinio Vaz",
        position: "FW",
        position_id: 27,
        numero: 34,
        age: "18",
        nationalite: "France",
        taille: 185,
        poids: null,
        image: "https://cdn.sportmonks.com/images/soccer/players/22/37713942.png",
        playerSlug: "robinio-vaz"
      },
      {
        id: 37729567,
        nom: "Keyliane Abdallah",
        displayName: "Keyliane Abdallah",
        position: "FW",
        position_id: 27,
        numero: 48,
        age: "19",
        nationalite: "France",
        taille: null,
        poids: null,
        image: "https://cdn.sportmonks.com/images/soccer/players/31/37729567.png",
        playerSlug: "keyliane-abdallah"
      }
    ]
  }
];