// Stats COMPLÃˆTES des joueurs de l'OM depuis SportMonks API
// Inclut TOUTES les saisons dans TOUS les clubs (pas seulement l'OM)
// GÃ©nÃ©rÃ© automatiquement

export interface PlayerSeasonStats {
  // MÃ©tadonnÃ©es
  team?: string;
  team_id?: number;
  league?: string;
  
  // Stats gÃ©nÃ©rales
  rating?: number | null;
  minutes?: number | null;
  appearences?: number | null;
  lineups?: number | null;
  captain?: number | null;
  substitutions?: number | null;
  touches?: number | null;
  
  // Stats offensives
  goals?: number | null;
  assists?: number | null;
  xg?: number | null;
  xa?: number | null;
  shots?: number | null;
  shots_on_target?: number | null;
  penalties_won?: number | null;
  penalties?: number | null;
  penalties_scored?: number | null;
  penalties_missed?: number | null;
  hit_woodwork?: number | null;
  offsides?: number | null;
  
  // Stats de passes
  passes?: number | null;
  passes_completed?: number | null;
  passes_accuracy?: number | null;
  key_passes?: number | null;
  crosses?: number | null;
  crosses_accurate?: number | null;
  
  // Stats de dribbles
  dribbles?: number | null;
  dribbles_successful?: number | null;
  
  // Stats dÃ©fensives
  tackles?: number | null;
  blocks?: number | null;
  interceptions?: number | null;
  clearances?: number | null;
  ground_duels?: number | null;
  ground_duels_won?: number | null;
  aerial_duels?: number | null;
  aerial_duels_won?: number | null;
  
  // Discipline
  fouls?: number | null;
  fouls_drawn?: number | null;
  yellow_cards?: number | null;
  red_cards?: number | null;
  yellowred_cards?: number | null;
  penalties_committed?: number | null;
  
  // Autres
  ball_losses?: number | null;
  ball_recoveries?: number | null;
  mistakes_leading_to_goals?: number | null;
  
  // Stats gardien
  saves?: number | null;
  punches?: number | null;
  inside_box_saves?: number | null;
  clean_sheets?: number | null;
  goals_conceded?: number | null;
  
  // CalculÃ©
  crosses_accuracy?: number | null;
}

export interface PlayerRealStats {
  displayName: string;
  position: string;
  jersey?: number;
  stats: {
    [seasonKey: string]: PlayerSeasonStats | null;
  };
}

export const omPlayersRealStats: { [playerId: number]: PlayerRealStats } = {
  37369302: {
    displayName: "Bamo Meïté",
    position: "",
    jersey: 18,
    stats: {
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.58,
        minutes: 24,
        appearences: 3,
        lineups: 0,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 0,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 1,
        clean_sheets: 1,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 24,
        passes_completed: 22,
        passes_accuracy: 91.67,
        key_passes: 0,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 0,
        blocks: 0,
        interceptions: 0,
        clearances: 0,
        fouls: 1,
        fouls_drawn: 1,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 1,
        duels: 4,
        duels_won: 2,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2023/2024 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.87,
        minutes: 631,
        appearences: 16,
        lineups: 6,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 1,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 9,
        clean_sheets: 4,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 481,
        passes_completed: 441,
        passes_accuracy: 91.68,
        key_passes: 1,
        crosses: 4,
        crosses_accurate: 0,
        tackles: 17,
        blocks: 5,
        interceptions: 10,
        clearances: 32,
        fouls: 10,
        fouls_drawn: 6,
        yellow_cards: 1,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 22,
        duels: 78,
        duels_won: 49,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 4,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  37713942: {
    displayName: "Robinio Vaz",
    position: "",
    jersey: 34,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.76,
        minutes: 20,
        appearences: 2,
        lineups: 0,
        captain: 0,
        touches: 0,
        goals: 1,
        assists: 0,
        xg: null,
        xa: null,
        shots: 1,
        shots_on_target: 1,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 1,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 3,
        passes_completed: 1,
        passes_accuracy: 33.33,
        key_passes: 0,
        crosses: 1,
        crosses_accurate: 0,
        tackles: 1,
        blocks: 0,
        interceptions: 1,
        clearances: 0,
        fouls: 1,
        fouls_drawn: 1,
        yellow_cards: 1,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 3,
        duels_won: 2,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.58,
        minutes: 74,
        appearences: 2,
        lineups: 0,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 2,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 0,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 7,
        passes_completed: 2,
        passes_accuracy: 28.57,
        key_passes: 0,
        crosses: 1,
        crosses_accurate: 0,
        tackles: 1,
        blocks: 0,
        interceptions: 0,
        clearances: 2,
        fouls: 1,
        fouls_drawn: 4,
        yellow_cards: 1,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 3,
        duels: 14,
        duels_won: 7,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 1,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  512560: {
    displayName: "Amir Murillo",
    position: "",
    jersey: 62,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.01,
        minutes: 168,
        appearences: 2,
        lineups: 2,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 1,
        shots_on_target: 0,
        hit_woodwork: 1,
        saves: 0,
        goals_conceded: 2,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 87,
        passes_completed: 77,
        passes_accuracy: 88.51,
        key_passes: 2,
        crosses: 4,
        crosses_accurate: 2,
        tackles: 2,
        blocks: 1,
        interceptions: 0,
        clearances: 3,
        fouls: 4,
        fouls_drawn: 1,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 2,
        duels: 10,
        duels_won: 5,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 1,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.11,
        minutes: 2436,
        appearences: 30,
        lineups: 27,
        captain: 0,
        touches: 0,
        goals: 1,
        assists: 3,
        xg: null,
        xa: null,
        shots: 13,
        shots_on_target: 4,
        hit_woodwork: 1,
        saves: 0,
        goals_conceded: 35,
        clean_sheets: 5,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 1698,
        passes_completed: 1521,
        passes_accuracy: 89.58,
        key_passes: 24,
        crosses: 37,
        crosses_accurate: 5,
        tackles: 48,
        blocks: 8,
        interceptions: 19,
        clearances: 65,
        fouls: 29,
        fouls_drawn: 26,
        yellow_cards: 3,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 43,
        duels: 206,
        duels_won: 130,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 1,
        ball_losses: 11,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2023/2024 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.05,
        minutes: 993,
        appearences: 16,
        lineups: 10,
        captain: 0,
        touches: 0,
        goals: 3,
        assists: 3,
        xg: null,
        xa: null,
        shots: 5,
        shots_on_target: 4,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 12,
        clean_sheets: 3,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 512,
        passes_completed: 434,
        passes_accuracy: 84.77,
        key_passes: 7,
        crosses: 16,
        crosses_accurate: 3,
        tackles: 22,
        blocks: 2,
        interceptions: 11,
        clearances: 29,
        fouls: 10,
        fouls_drawn: 10,
        yellow_cards: 3,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 15,
        duels: 103,
        duels_won: 59,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 6,
        ball_losses: 8,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  32390: {
    displayName: "Ulisses Garcia",
    position: "",
    jersey: 6,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.33,
        minutes: 102,
        appearences: 2,
        lineups: 1,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 1,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 3,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 47,
        passes_completed: 44,
        passes_accuracy: 93.62,
        key_passes: 0,
        crosses: 1,
        crosses_accurate: 0,
        tackles: 2,
        blocks: 0,
        interceptions: 0,
        clearances: 2,
        fouls: 2,
        fouls_drawn: 0,
        yellow_cards: 1,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 5,
        duels_won: 2,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.92,
        minutes: 929,
        appearences: 20,
        lineups: 10,
        captain: 0,
        touches: 0,
        goals: 2,
        assists: 2,
        xg: null,
        xa: null,
        shots: 8,
        shots_on_target: 2,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 13,
        clean_sheets: 2,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 521,
        passes_completed: 458,
        passes_accuracy: 87.91,
        key_passes: 9,
        crosses: 35,
        crosses_accurate: 7,
        tackles: 14,
        blocks: 1,
        interceptions: 8,
        clearances: 16,
        fouls: 8,
        fouls_drawn: 9,
        yellow_cards: 2,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 16,
        duels: 95,
        duels_won: 48,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 2,
        ball_losses: 11,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2023/2024 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.88,
        minutes: 905,
        appearences: 13,
        lineups: 10,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 11,
        shots_on_target: 5,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 14,
        clean_sheets: 1,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 433,
        passes_completed: 360,
        passes_accuracy: 83.14,
        key_passes: 8,
        crosses: 48,
        crosses_accurate: 7,
        tackles: 23,
        blocks: 3,
        interceptions: 5,
        clearances: 9,
        fouls: 15,
        fouls_drawn: 11,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 17,
        duels: 109,
        duels_won: 59,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 13,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 1,
      },
    }
  },
  37541144: {
    displayName: "Bilal Nadir",
    position: "",
    jersey: 26,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.97,
        minutes: 27,
        appearences: 1,
        lineups: 0,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 2,
        xg: null,
        xa: null,
        shots: 0,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 0,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 9,
        passes_completed: 7,
        passes_accuracy: 77.78,
        key_passes: 2,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 2,
        blocks: 0,
        interceptions: 0,
        clearances: 0,
        fouls: 0,
        fouls_drawn: 0,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 3,
        duels_won: 3,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 1,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.86,
        minutes: 387,
        appearences: 15,
        lineups: 5,
        captain: 0,
        touches: 0,
        goals: 1,
        assists: 0,
        xg: null,
        xa: null,
        shots: 8,
        shots_on_target: 3,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 8,
        clean_sheets: 2,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 245,
        passes_completed: 218,
        passes_accuracy: 88.98,
        key_passes: 7,
        crosses: 6,
        crosses_accurate: 2,
        tackles: 10,
        blocks: 1,
        interceptions: 4,
        clearances: 7,
        fouls: 4,
        fouls_drawn: 11,
        yellow_cards: 2,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 3,
        duels: 46,
        duels_won: 28,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 8,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2023/2024 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.94,
        minutes: 111,
        appearences: 5,
        lineups: 1,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 1,
        shots_on_target: 0,
        hit_woodwork: 1,
        saves: 0,
        goals_conceded: 2,
        clean_sheets: 2,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 45,
        passes_completed: 38,
        passes_accuracy: 84.44,
        key_passes: 2,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 4,
        blocks: 0,
        interceptions: 2,
        clearances: 2,
        fouls: 4,
        fouls_drawn: 2,
        yellow_cards: 1,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 14,
        duels_won: 7,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  95776: {
    displayName: "Neal Maupay",
    position: "",
    jersey: 7,
    stats: {
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.87,
        minutes: 1044,
        appearences: 22,
        lineups: 13,
        captain: 0,
        touches: 0,
        goals: 4,
        assists: 4,
        xg: null,
        xa: null,
        shots: 19,
        shots_on_target: 10,
        hit_woodwork: 2,
        saves: 0,
        goals_conceded: 20,
        clean_sheets: 3,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 288,
        passes_completed: 242,
        passes_accuracy: 84.03,
        key_passes: 13,
        crosses: 1,
        crosses_accurate: 0,
        tackles: 9,
        blocks: 0,
        interceptions: 2,
        clearances: 1,
        fouls: 10,
        fouls_drawn: 17,
        yellow_cards: 2,
        red_cards: 0,
        yellowred_cards: 1,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 7,
        duels: 88,
        duels_won: 37,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 2,
        ball_losses: 16,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  433458: {
    displayName: "Amine Gouiri",
    position: "",
    jersey: 9,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.76,
        minutes: 176,
        appearences: 2,
        lineups: 2,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 4,
        shots_on_target: 2,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 2,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 57,
        passes_completed: 49,
        passes_accuracy: 85.96,
        key_passes: 4,
        crosses: 11,
        crosses_accurate: 5,
        tackles: 2,
        blocks: 0,
        interceptions: 1,
        clearances: 0,
        fouls: 0,
        fouls_drawn: 2,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 9,
        duels_won: 4,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 2,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.74,
        minutes: 1052,
        appearences: 14,
        lineups: 12,
        captain: 0,
        touches: 0,
        goals: 10,
        assists: 3,
        xg: null,
        xa: null,
        shots: 51,
        shots_on_target: 25,
        hit_woodwork: 1,
        saves: 0,
        goals_conceded: 18,
        clean_sheets: 2,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 293,
        passes_completed: 263,
        passes_accuracy: 89.76,
        key_passes: 27,
        crosses: 57,
        crosses_accurate: 21,
        tackles: 7,
        blocks: 0,
        interceptions: 1,
        clearances: 1,
        fouls: 11,
        fouls_drawn: 7,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 2,
        duels: 72,
        duels_won: 26,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 5,
        ball_losses: 15,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  20333643: {
    displayName: "Mason Greenwood",
    position: "",
    jersey: 10,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.95,
        minutes: 180,
        appearences: 2,
        lineups: 2,
        captain: 0,
        touches: 0,
        goals: 1,
        assists: 2,
        xg: null,
        xa: null,
        shots: 8,
        shots_on_target: 1,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 3,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 107,
        passes_completed: 91,
        passes_accuracy: 85.05,
        key_passes: 8,
        crosses: 7,
        crosses_accurate: 3,
        tackles: 1,
        blocks: 0,
        interceptions: 0,
        clearances: 0,
        fouls: 2,
        fouls_drawn: 3,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 20,
        duels_won: 8,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 2,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 2,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.68,
        minutes: 2819,
        appearences: 34,
        lineups: 32,
        captain: 0,
        touches: 0,
        goals: 21,
        assists: 5,
        xg: null,
        xa: null,
        shots: 120,
        shots_on_target: 57,
        hit_woodwork: 1,
        saves: 0,
        goals_conceded: 41,
        clean_sheets: 5,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 1263,
        passes_completed: 1052,
        passes_accuracy: 83.29,
        key_passes: 50,
        crosses: 109,
        crosses_accurate: 28,
        tackles: 36,
        blocks: 1,
        interceptions: 13,
        clearances: 5,
        fouls: 24,
        fouls_drawn: 36,
        yellow_cards: 3,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 8,
        duels: 294,
        duels_won: 133,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 9,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 2,
        ball_losses: 45,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 1,
      },
    }
  },
  37737405: {
    displayName: "Darryl Bakola",
    position: "",
    jersey: 50,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: null,
        minutes: 5,
        appearences: 2,
        lineups: 0,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 0,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 1,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 9,
        passes_completed: 9,
        passes_accuracy: 100,
        key_passes: 0,
        crosses: 1,
        crosses_accurate: 0,
        tackles: 0,
        blocks: 0,
        interceptions: 0,
        clearances: 0,
        fouls: 0,
        fouls_drawn: 1,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 2,
        duels_won: 1,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.5,
        minutes: 12,
        appearences: 2,
        lineups: 0,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 0,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 1,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 13,
        passes_completed: 12,
        passes_accuracy: 92.31,
        key_passes: 0,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 1,
        blocks: 0,
        interceptions: 0,
        clearances: 0,
        fouls: 3,
        fouls_drawn: 0,
        yellow_cards: 1,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 6,
        duels_won: 1,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 1,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  37729567: {
    displayName: "Keyliane Abdallah",
    position: "",
    jersey: 48,
    stats: {
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.83,
        minutes: 2,
        appearences: 1,
        lineups: 0,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 0,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 0,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 2,
        passes_completed: 2,
        passes_accuracy: 100,
        key_passes: 0,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 1,
        blocks: 0,
        interceptions: 0,
        clearances: 0,
        fouls: 0,
        fouls_drawn: 0,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 1,
        duels_won: 1,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2023/2024 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.43,
        minutes: 3,
        appearences: 1,
        lineups: 0,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 0,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 0,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 1,
        passes_completed: 1,
        passes_accuracy: 100,
        key_passes: 0,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 0,
        blocks: 0,
        interceptions: 0,
        clearances: 0,
        fouls: 0,
        fouls_drawn: 0,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 1,
        duels_won: 0,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  586846: {
    displayName: "Derek Cornelius",
    position: "",
    jersey: 13,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: null,
        minutes: 1,
        appearences: 1,
        lineups: 0,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 0,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 0,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 0,
        passes_completed: 0,
        passes_accuracy: null,
        key_passes: 0,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 0,
        blocks: 0,
        interceptions: 0,
        clearances: 0,
        fouls: 0,
        fouls_drawn: 0,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 0,
        duels_won: 0,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.96,
        minutes: 1424,
        appearences: 21,
        lineups: 17,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 9,
        shots_on_target: 1,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 18,
        clean_sheets: 4,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 1349,
        passes_completed: 1265,
        passes_accuracy: 93.77,
        key_passes: 4,
        crosses: 4,
        crosses_accurate: 1,
        tackles: 25,
        blocks: 11,
        interceptions: 13,
        clearances: 50,
        fouls: 25,
        fouls_drawn: 14,
        yellow_cards: 6,
        red_cards: 0,
        yellowred_cards: 2,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 32,
        duels: 118,
        duels_won: 72,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 2,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  28575687: {
    displayName: "CJ Egan-Riley",
    position: "",
    jersey: 4,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.07,
        minutes: 180,
        appearences: 2,
        lineups: 2,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 0,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 3,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 176,
        passes_completed: 164,
        passes_accuracy: 93.18,
        key_passes: 2,
        crosses: 1,
        crosses_accurate: 0,
        tackles: 4,
        blocks: 4,
        interceptions: 0,
        clearances: 9,
        fouls: 0,
        fouls_drawn: 2,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 1,
        duels: 11,
        duels_won: 8,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  13171199: {
    displayName: "Leonardo Balerdi ",
    position: "",
    jersey: 5,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.01,
        minutes: 180,
        appearences: 2,
        lineups: 2,
        captain: 2,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 4,
        shots_on_target: 2,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 3,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 191,
        passes_completed: 184,
        passes_accuracy: 96.34,
        key_passes: 1,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 5,
        blocks: 1,
        interceptions: 0,
        clearances: 6,
        fouls: 1,
        fouls_drawn: 2,
        yellow_cards: 1,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 5,
        duels: 17,
        duels_won: 13,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.09,
        minutes: 2276,
        appearences: 27,
        lineups: 27,
        captain: 26,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 15,
        shots_on_target: 2,
        hit_woodwork: 1,
        saves: 0,
        goals_conceded: 34,
        clean_sheets: 4,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 2506,
        passes_completed: 2354,
        passes_accuracy: 93.93,
        key_passes: 8,
        crosses: 2,
        crosses_accurate: 0,
        tackles: 56,
        blocks: 14,
        interceptions: 38,
        clearances: 74,
        fouls: 28,
        fouls_drawn: 20,
        yellow_cards: 8,
        red_cards: 0,
        yellowred_cards: 1,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 40,
        duels: 224,
        duels_won: 136,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 13,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 1,
      },
      "2023/2024 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.32,
        minutes: 2275,
        appearences: 27,
        lineups: 26,
        captain: 0,
        touches: 0,
        goals: 2,
        assists: 0,
        xg: null,
        xa: null,
        shots: 13,
        shots_on_target: 4,
        hit_woodwork: 1,
        saves: 0,
        goals_conceded: 31,
        clean_sheets: 5,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 1618,
        passes_completed: 1398,
        passes_accuracy: 86.4,
        key_passes: 5,
        crosses: 3,
        crosses_accurate: 0,
        tackles: 77,
        blocks: 15,
        interceptions: 54,
        clearances: 80,
        fouls: 25,
        fouls_drawn: 24,
        yellow_cards: 5,
        red_cards: 0,
        yellowred_cards: 1,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 56,
        duels: 260,
        duels_won: 166,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 1,
        ball_losses: 9,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  608285: {
    displayName: "Angel Gomes",
    position: "",
    jersey: 8,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.25,
        minutes: 176,
        appearences: 2,
        lineups: 2,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 1,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 2,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 180,
        passes_completed: 167,
        passes_accuracy: 92.78,
        key_passes: 4,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 3,
        blocks: 0,
        interceptions: 1,
        clearances: 1,
        fouls: 2,
        fouls_drawn: 1,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 8,
        duels_won: 5,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  537332: {
    displayName: "Timothy Weah",
    position: "",
    jersey: 22,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.72,
        minutes: 107,
        appearences: 2,
        lineups: 1,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 1,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 3,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 51,
        passes_completed: 47,
        passes_accuracy: 92.16,
        key_passes: 2,
        crosses: 4,
        crosses_accurate: 1,
        tackles: 4,
        blocks: 0,
        interceptions: 1,
        clearances: 1,
        fouls: 2,
        fouls_drawn: 1,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 10,
        duels_won: 5,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  31739: {
    displayName: "Pierre-Emerick Aubameyang",
    position: "",
    jersey: 97,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.42,
        minutes: 101,
        appearences: 2,
        lineups: 1,
        captain: 0,
        touches: 0,
        goals: 2,
        assists: 0,
        xg: null,
        xa: null,
        shots: 3,
        shots_on_target: 2,
        hit_woodwork: 1,
        saves: 0,
        goals_conceded: 3,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 21,
        passes_completed: 18,
        passes_accuracy: 85.71,
        key_passes: 0,
        crosses: 1,
        crosses_accurate: 0,
        tackles: 0,
        blocks: 0,
        interceptions: 0,
        clearances: 0,
        fouls: 1,
        fouls_drawn: 1,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 4,
        duels_won: 1,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 1,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2023/2024 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.37,
        minutes: 2628,
        appearences: 34,
        lineups: 30,
        captain: 0,
        touches: 0,
        goals: 16,
        assists: 8,
        xg: null,
        xa: null,
        shots: 115,
        shots_on_target: 51,
        hit_woodwork: 6,
        saves: 0,
        goals_conceded: 37,
        clean_sheets: 7,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 605,
        passes_completed: 431,
        passes_accuracy: 71.24,
        key_passes: 27,
        crosses: 43,
        crosses_accurate: 9,
        tackles: 22,
        blocks: 5,
        interceptions: 6,
        clearances: 23,
        fouls: 9,
        fouls_drawn: 20,
        yellow_cards: 4,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 25,
        duels: 186,
        duels_won: 85,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 4,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 21,
        ball_losses: 23,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  186456: {
    displayName: "Rubén Blanco",
    position: "",
    jersey: 36,
    stats: {
      "2023/2024 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.24,
        minutes: 121,
        appearences: 2,
        lineups: 1,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 0,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 4,
        goals_conceded: 2,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 3,
        passes: 45,
        passes_completed: 37,
        passes_accuracy: 82.22,
        key_passes: 0,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 0,
        blocks: 0,
        interceptions: 0,
        clearances: 0,
        fouls: 0,
        fouls_drawn: 0,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 1,
        duels: 1,
        duels_won: 1,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  130063: {
    displayName: "Pol Lirola",
    position: "",
    jersey: 29,
    stats: {
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.69,
        minutes: 675,
        appearences: 19,
        lineups: 5,
        captain: 0,
        touches: 0,
        goals: 1,
        assists: 2,
        xg: null,
        xa: null,
        shots: 6,
        shots_on_target: 1,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 14,
        clean_sheets: 3,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 338,
        passes_completed: 292,
        passes_accuracy: 86.39,
        key_passes: 8,
        crosses: 14,
        crosses_accurate: 2,
        tackles: 14,
        blocks: 2,
        interceptions: 4,
        clearances: 12,
        fouls: 9,
        fouls_drawn: 9,
        yellow_cards: 1,
        red_cards: 1,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 4,
        duels: 58,
        duels_won: 28,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 4,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  95696: {
    displayName: "Geoffrey Kondogbia",
    position: "",
    jersey: 19,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.9,
        minutes: 46,
        appearences: 1,
        lineups: 1,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 0,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 0,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 40,
        passes_completed: 37,
        passes_accuracy: 92.5,
        key_passes: 0,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 0,
        blocks: 0,
        interceptions: 0,
        clearances: 4,
        fouls: 0,
        fouls_drawn: 0,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 0,
        duels_won: 0,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.12,
        minutes: 2021,
        appearences: 25,
        lineups: 22,
        captain: 1,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 8,
        shots_on_target: 1,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 31,
        clean_sheets: 4,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 1783,
        passes_completed: 1653,
        passes_accuracy: 92.71,
        key_passes: 5,
        crosses: 4,
        crosses_accurate: 2,
        tackles: 60,
        blocks: 6,
        interceptions: 24,
        clearances: 61,
        fouls: 19,
        fouls_drawn: 17,
        yellow_cards: 1,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 27,
        duels: 171,
        duels_won: 114,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 1,
        ball_losses: 14,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2023/2024 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.03,
        minutes: 1458,
        appearences: 26,
        lineups: 15,
        captain: 5,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 8,
        shots_on_target: 1,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 19,
        clean_sheets: 5,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 936,
        passes_completed: 824,
        passes_accuracy: 88.03,
        key_passes: 10,
        crosses: 2,
        crosses_accurate: 1,
        tackles: 49,
        blocks: 4,
        interceptions: 30,
        clearances: 25,
        fouls: 25,
        fouls_drawn: 29,
        yellow_cards: 3,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 17,
        duels: 170,
        duels_won: 103,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 2,
        ball_losses: 14,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  34455209: {
    displayName: "Jonathan Rowe",
    position: "",
    jersey: 17,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.4,
        minutes: 63,
        appearences: 1,
        lineups: 1,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 5,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 0,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 23,
        passes_completed: 18,
        passes_accuracy: 78.26,
        key_passes: 1,
        crosses: 5,
        crosses_accurate: 1,
        tackles: 0,
        blocks: 0,
        interceptions: 1,
        clearances: 0,
        fouls: 2,
        fouls_drawn: 2,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 1,
        duels: 7,
        duels_won: 3,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.95,
        minutes: 800,
        appearences: 28,
        lineups: 6,
        captain: 0,
        touches: 0,
        goals: 3,
        assists: 3,
        xg: null,
        xa: null,
        shots: 36,
        shots_on_target: 15,
        hit_woodwork: 1,
        saves: 0,
        goals_conceded: 15,
        clean_sheets: 3,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 260,
        passes_completed: 224,
        passes_accuracy: 86.15,
        key_passes: 18,
        crosses: 28,
        crosses_accurate: 7,
        tackles: 16,
        blocks: 2,
        interceptions: 2,
        clearances: 5,
        fouls: 14,
        fouls_drawn: 27,
        yellow_cards: 1,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 8,
        duels: 140,
        duels_won: 70,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 7,
        ball_losses: 15,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  21803033: {
    displayName: "Azzedine Ounahi",
    position: "",
    stats: {
      "2023/2024 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7,
        minutes: 1215,
        appearences: 21,
        lineups: 15,
        captain: 0,
        touches: 0,
        goals: 2,
        assists: 0,
        xg: null,
        xa: null,
        shots: 16,
        shots_on_target: 4,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 16,
        clean_sheets: 3,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 790,
        passes_completed: 716,
        passes_accuracy: 90.63,
        key_passes: 15,
        crosses: 22,
        crosses_accurate: 4,
        tackles: 25,
        blocks: 1,
        interceptions: 12,
        clearances: 7,
        fouls: 16,
        fouls_drawn: 24,
        yellow_cards: 3,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 3,
        duels: 140,
        duels_won: 59,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 1,
        ball_losses: 17,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  95694: {
    displayName: "Adrien Rabiot",
    position: "",
    jersey: 25,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.6,
        minutes: 90,
        appearences: 1,
        lineups: 1,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 1,
        shots_on_target: 0,
        hit_woodwork: 1,
        saves: 0,
        goals_conceded: 1,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 40,
        passes_completed: 39,
        passes_accuracy: 97.5,
        key_passes: 4,
        crosses: 8,
        crosses_accurate: 4,
        tackles: 0,
        blocks: 0,
        interceptions: 0,
        clearances: 1,
        fouls: 2,
        fouls_drawn: 1,
        yellow_cards: 1,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 5,
        duels_won: 1,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.49,
        minutes: 2483,
        appearences: 29,
        lineups: 27,
        captain: 1,
        touches: 0,
        goals: 9,
        assists: 4,
        xg: null,
        xa: null,
        shots: 48,
        shots_on_target: 24,
        hit_woodwork: 2,
        saves: 0,
        goals_conceded: 39,
        clean_sheets: 4,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 1485,
        passes_completed: 1293,
        passes_accuracy: 87.07,
        key_passes: 29,
        crosses: 41,
        crosses_accurate: 6,
        tackles: 49,
        blocks: 2,
        interceptions: 22,
        clearances: 32,
        fouls: 53,
        fouls_drawn: 33,
        yellow_cards: 4,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 35,
        duels: 285,
        duels_won: 141,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 12,
        ball_losses: 33,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  96691: {
    displayName: "Amine Harit",
    position: "",
    jersey: 11,
    stats: {
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.98,
        minutes: 522,
        appearences: 13,
        lineups: 8,
        captain: 0,
        touches: 0,
        goals: 2,
        assists: 4,
        xg: null,
        xa: null,
        shots: 8,
        shots_on_target: 5,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 7,
        clean_sheets: 2,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 244,
        passes_completed: 212,
        passes_accuracy: 86.89,
        key_passes: 19,
        crosses: 7,
        crosses_accurate: 1,
        tackles: 8,
        blocks: 0,
        interceptions: 3,
        clearances: 1,
        fouls: 6,
        fouls_drawn: 15,
        yellow_cards: 1,
        red_cards: 1,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 1,
        duels: 63,
        duels_won: 32,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 13,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2023/2024 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.21,
        minutes: 1828,
        appearences: 28,
        lineups: 21,
        captain: 0,
        touches: 0,
        goals: 1,
        assists: 2,
        xg: null,
        xa: null,
        shots: 33,
        shots_on_target: 8,
        hit_woodwork: 1,
        saves: 0,
        goals_conceded: 20,
        clean_sheets: 7,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 907,
        passes_completed: 791,
        passes_accuracy: 87.21,
        key_passes: 39,
        crosses: 39,
        crosses_accurate: 12,
        tackles: 29,
        blocks: 4,
        interceptions: 12,
        clearances: 3,
        fouls: 19,
        fouls_drawn: 51,
        yellow_cards: 5,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 4,
        duels: 243,
        duels_won: 124,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 1,
        ball_losses: 38,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  1744: {
    displayName: "Pierre-Emile Højbjerg",
    position: "",
    jersey: 23,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.35,
        minutes: 180,
        appearences: 2,
        lineups: 2,
        captain: 0,
        touches: 0,
        goals: 1,
        assists: 0,
        xg: null,
        xa: null,
        shots: 5,
        shots_on_target: 1,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 3,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 211,
        passes_completed: 197,
        passes_accuracy: 93.36,
        key_passes: 0,
        crosses: 1,
        crosses_accurate: 0,
        tackles: 1,
        blocks: 0,
        interceptions: 1,
        clearances: 2,
        fouls: 1,
        fouls_drawn: 2,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 4,
        duels: 13,
        duels_won: 8,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 1,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.48,
        minutes: 2666,
        appearences: 30,
        lineups: 30,
        captain: 6,
        touches: 0,
        goals: 2,
        assists: 4,
        xg: null,
        xa: null,
        shots: 33,
        shots_on_target: 8,
        hit_woodwork: 1,
        saves: 0,
        goals_conceded: 36,
        clean_sheets: 5,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 2856,
        passes_completed: 2646,
        passes_accuracy: 92.65,
        key_passes: 44,
        crosses: 19,
        crosses_accurate: 9,
        tackles: 64,
        blocks: 5,
        interceptions: 41,
        clearances: 30,
        fouls: 30,
        fouls_drawn: 39,
        yellow_cards: 5,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 21,
        duels: 249,
        duels_won: 131,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 29,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  20315925: {
    displayName: "Faris Moumbagna",
    position: "",
    stats: {
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.53,
        minutes: 8,
        appearences: 1,
        lineups: 0,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 0,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 0,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 0,
        passes_completed: 0,
        passes_accuracy: null,
        key_passes: 0,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 0,
        blocks: 0,
        interceptions: 0,
        clearances: 0,
        fouls: 1,
        fouls_drawn: 0,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 2,
        duels_won: 0,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 1,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2023/2024 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.7,
        minutes: 543,
        appearences: 13,
        lineups: 5,
        captain: 0,
        touches: 0,
        goals: 3,
        assists: 1,
        xg: null,
        xa: null,
        shots: 16,
        shots_on_target: 5,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 10,
        clean_sheets: 1,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 99,
        passes_completed: 72,
        passes_accuracy: 72.73,
        key_passes: 4,
        crosses: 4,
        crosses_accurate: 1,
        tackles: 2,
        blocks: 0,
        interceptions: 4,
        clearances: 1,
        fouls: 12,
        fouls_drawn: 11,
        yellow_cards: 1,
        red_cards: 0,
        yellowred_cards: 1,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 7,
        duels: 65,
        duels_won: 21,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 4,
        ball_losses: 7,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  37657133: {
    displayName: "François Mughe",
    position: "",
    jersey: 24,
    stats: {
      "2023/2024 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.73,
        minutes: 176,
        appearences: 5,
        lineups: 2,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 3,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 0,
        goals_conceded: 1,
        clean_sheets: 3,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 0,
        passes: 34,
        passes_completed: 22,
        passes_accuracy: 64.71,
        key_passes: 2,
        crosses: 7,
        crosses_accurate: 3,
        tackles: 0,
        blocks: 0,
        interceptions: 1,
        clearances: 1,
        fouls: 3,
        fouls_drawn: 8,
        yellow_cards: 1,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 2,
        duels: 26,
        duels_won: 12,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 1,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
    }
  },
  186418: {
    displayName: "Gerónimo Rulli",
    position: "",
    jersey: 1,
    stats: {
      "2025/2026 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 6.78,
        minutes: 180,
        appearences: 2,
        lineups: 2,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 0,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 6,
        goals_conceded: 3,
        clean_sheets: 0,
        penalties_saved: 0,
        punches: 0,
        inside_box_saves: 4,
        passes: 54,
        passes_completed: 47,
        passes_accuracy: 87.04,
        key_passes: 0,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 0,
        blocks: 0,
        interceptions: 0,
        clearances: 5,
        fouls: 0,
        fouls_drawn: 0,
        yellow_cards: 0,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 0,
        duels: 0,
        duels_won: 0,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 0,
      },
      "2024/2025 (Ligue 1, Olympique Marseille)": {
        team: "Olympique Marseille",
        team_id: 44,
        league: "Ligue 1",
        rating: 7.02,
        minutes: 3060,
        appearences: 34,
        lineups: 34,
        captain: 0,
        touches: 0,
        goals: 0,
        assists: 0,
        xg: null,
        xa: null,
        shots: 0,
        shots_on_target: 0,
        hit_woodwork: 0,
        saves: 93,
        goals_conceded: 47,
        clean_sheets: 5,
        penalties_saved: 3,
        punches: 0,
        inside_box_saves: 64,
        passes: 1069,
        passes_completed: 929,
        passes_accuracy: 86.9,
        key_passes: 2,
        crosses: 0,
        crosses_accurate: 0,
        tackles: 5,
        blocks: 0,
        interceptions: 1,
        clearances: 33,
        fouls: 2,
        fouls_drawn: 11,
        yellow_cards: 1,
        red_cards: 0,
        yellowred_cards: 0,
        ground_duels: 0,
        ground_duels_won: 0,
        aerial_duels: 0,
        aerial_duels_won: 10,
        duels: 29,
        duels_won: 23,
        dribbles: 0,
        dribbles_successful: 0,
        penalties: 0,
        penalties_won: 0,
        penalties_scored: 0,
        penalties_missed: 0,
        penalties_committed: 0,
        offsides: 0,
        ball_losses: 0,
        ball_recoveries: 0,
        mistakes_leading_to_goals: 4,
      },
    }
  },
};
