// Données Ligue 1 générées automatiquement
export const ligue1Data = {
  "psg": {
    "club_id": 591,
    "club_name": "Paris Saint-Germain",
    "players": [
      {
        "id": 7698421,
        "nom": "Arnau Tenas",
        "position": "Gardien",
        "position_id": 24,
        "age": "2001-05-30",
        "nationalite": "Espagne",
        "numero": 80,
        "taille": 185,
        "poids": null
      },
      {
        "id": 129771,
        "nom": "Gianluigi Donnarumma",
        "position": "Gardien",
        "position_id": 24,
        "age": "1999-02-25",
        "nationalite": "Italie",
        "numero": 1,
        "taille": 196,
        "poids": 90
      },
      {
        "id": 17187774,
        "nom": "Lucas Chevalier",
        "position": "Gardien",
        "position_id": 24,
        "age": "2001-11-06",
        "nationalite": "France",
        "numero": null,
        "taille": 189,
        "poids": null
      },
      {
        "id": 171922,
        "nom": "Matvey Safonov",
        "position": "Gardien",
        "position_id": 24,
        "age": "1999-02-25",
        "nationalite": "Russie",
        "numero": 39,
        "taille": 192,
        "poids": 85
      },
      {
        "id": 37714950,
        "nom": "Renato Marin",
        "position": "Gardien",
        "position_id": 24,
        "age": "2006-07-10",
        "nationalite": "Italie",
        "numero": null,
        "taille": 193,
        "poids": null
      },
      {
        "id": 187260,
        "nom": "Achraf Hakimi",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1998-11-04",
        "nationalite": "Maroc",
        "numero": 2,
        "taille": 181,
        "poids": 65
      },
      {
        "id": 24065255,
        "nom": "Ilya Zabarnyi",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2002-09-01",
        "nationalite": "Ukraine",
        "numero": null,
        "taille": 189,
        "poids": null
      },
      {
        "id": 37562940,
        "nom": "Lucas Beraldo",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2003-11-24",
        "nationalite": "Brésil",
        "numero": 4,
        "taille": 186,
        "poids": null
      },
      {
        "id": 186797,
        "nom": "Lucas Hernández",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1996-02-14",
        "nationalite": "France",
        "numero": 21,
        "taille": 184,
        "poids": 76
      },
      {
        "id": 96208,
        "nom": "Marquinhos ",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1994-05-14",
        "nationalite": "Brésil",
        "numero": 5,
        "taille": 183,
        "poids": 75
      },
      {
        "id": 37262099,
        "nom": "Nuno Mendes",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2002-06-19",
        "nationalite": "Portugal",
        "numero": 25,
        "taille": 180,
        "poids": null
      },
      {
        "id": 96573,
        "nom": "Presnel Kimpembe",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1995-08-13",
        "nationalite": "France",
        "numero": 3,
        "taille": 183,
        "poids": 71
      },
      {
        "id": 12393419,
        "nom": "Willian Pacho",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2001-10-16",
        "nationalite": "Équateur",
        "numero": 51,
        "taille": 187,
        "poids": null
      },
      {
        "id": 186968,
        "nom": "Carlos Soler",
        "position": "Milieu",
        "position_id": 26,
        "age": "1997-01-02",
        "nationalite": "Espagne",
        "numero": 28,
        "taille": 180,
        "poids": 76
      },
      {
        "id": 186735,
        "nom": "Fabián Ruiz",
        "position": "Milieu",
        "position_id": 26,
        "age": "1996-04-03",
        "nationalite": "Espagne",
        "numero": 8,
        "taille": 189,
        "poids": 70
      },
      {
        "id": 37592729,
        "nom": "João Neves",
        "position": "Milieu",
        "position_id": 26,
        "age": "2004-09-27",
        "nationalite": "Portugal",
        "numero": 87,
        "taille": 174,
        "poids": null
      },
      {
        "id": 186668,
        "nom": "Marco Asensio",
        "position": "Milieu",
        "position_id": 26,
        "age": "1996-01-21",
        "nationalite": "Espagne",
        "numero": 11,
        "taille": 182,
        "poids": 76
      },
      {
        "id": 32387,
        "nom": "Renato Sanches",
        "position": "Milieu",
        "position_id": 26,
        "age": "1997-08-18",
        "nationalite": "Portugal",
        "numero": 18,
        "taille": 176,
        "poids": 70
      },
      {
        "id": 37656838,
        "nom": "Senny Mayulu",
        "position": "Milieu",
        "position_id": 26,
        "age": "2006-05-17",
        "nationalite": "France",
        "numero": 24,
        "taille": 183,
        "poids": null
      },
      {
        "id": 4545430,
        "nom": "Vitinha",
        "position": "Milieu",
        "position_id": 26,
        "age": "2000-02-13",
        "nationalite": "Portugal",
        "numero": 17,
        "taille": 172,
        "poids": null
      },
      {
        "id": 37593237,
        "nom": "Warren Zaïre-Emery",
        "position": "Milieu",
        "position_id": 26,
        "age": "2006-03-08",
        "nationalite": "France",
        "numero": 33,
        "taille": 178,
        "poids": null
      },
      {
        "id": 37317369,
        "nom": "Bradley Barcola",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2002-09-02",
        "nationalite": "France",
        "numero": 29,
        "taille": 182,
        "poids": null
      },
      {
        "id": 37590938,
        "nom": "Désiré Doué",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2005-06-03",
        "nationalite": "France",
        "numero": 14,
        "taille": 181,
        "poids": null
      },
      {
        "id": 23278610,
        "nom": "Gonçalo Ramos",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2001-06-20",
        "nationalite": "Portugal",
        "numero": 9,
        "taille": 185,
        "poids": null
      },
      {
        "id": 37726575,
        "nom": "Ibrahim Mbaye",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2008-01-24",
        "nationalite": "France",
        "numero": 49,
        "taille": 175,
        "poids": null
      },
      {
        "id": 9967153,
        "nom": "Kang-in Lee",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2001-02-19",
        "nationalite": "Corée du Sud",
        "numero": 19,
        "taille": 174,
        "poids": 68
      },
      {
        "id": 1479337,
        "nom": "Khvicha Kvaratskhelia",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2001-02-12",
        "nationalite": "Georgia",
        "numero": 7,
        "taille": 183,
        "poids": 70
      },
      {
        "id": 32403,
        "nom": "Ousmane Dembélé",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1997-05-15",
        "nationalite": "France",
        "numero": 10,
        "taille": 178,
        "poids": 67
      },
      {
        "id": 432872,
        "nom": "Randal Kolo Muani",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1998-12-05",
        "nationalite": "France",
        "numero": 23,
        "taille": 187,
        "poids": 73
      }
    ]
  },
  "marseille": {
    "club_id": 44,
    "club_name": "Olympique de Marseille",
    "players": [
      {
        "id": 186418,
        "nom": "Gerónimo Rulli",
        "position": "Gardien",
        "position_id": 24,
        "age": "1992-05-20",
        "nationalite": "Argentine",
        "numero": 1,
        "taille": 189,
        "poids": 84
      },
      {
        "id": 29186,
        "nom": "Jeffrey de Lange",
        "position": "Gardien",
        "position_id": 24,
        "age": "1998-04-01",
        "nationalite": "Pays-Bas",
        "numero": 12,
        "taille": 190,
        "poids": null
      },
      {
        "id": 37593233,
        "nom": "Jelle Van Neck",
        "position": "Gardien",
        "position_id": 24,
        "age": "2004-03-07",
        "nationalite": "Belgique",
        "numero": 40,
        "taille": 191,
        "poids": null
      },
      {
        "id": 186456,
        "nom": "Rubén Blanco",
        "position": "Gardien",
        "position_id": 24,
        "age": "1995-07-25",
        "nationalite": "Espagne",
        "numero": 36,
        "taille": 188,
        "poids": 70
      },
      {
        "id": 512560,
        "nom": "Amir Murillo",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1996-02-11",
        "nationalite": "Panama",
        "numero": 62,
        "taille": 184,
        "poids": 75
      },
      {
        "id": 37369302,
        "nom": "Bamo Meïté",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2001-12-03",
        "nationalite": "France",
        "numero": 18,
        "taille": 184,
        "poids": null
      },
      {
        "id": 28575687,
        "nom": "CJ Egan-Riley",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2003-01-02",
        "nationalite": "Angleterre",
        "numero": 4,
        "taille": 183,
        "poids": null
      },
      {
        "id": 586846,
        "nom": "Derek Cornelius",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1997-11-25",
        "nationalite": "Canada",
        "numero": 13,
        "taille": 187,
        "poids": 86
      },
      {
        "id": 335521,
        "nom": "Facundo Medina",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1999-05-28",
        "nationalite": "Argentine",
        "numero": 32,
        "taille": 184,
        "poids": 78
      },
      {
        "id": 13171199,
        "nom": "Leonardo Balerdi ",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1999-01-26",
        "nationalite": "Argentine",
        "numero": 5,
        "taille": 187,
        "poids": 85
      },
      {
        "id": 130063,
        "nom": "Pol Lirola",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1997-08-13",
        "nationalite": "Espagne",
        "numero": 29,
        "taille": 183,
        "poids": 70
      },
      {
        "id": 32390,
        "nom": "Ulisses Garcia",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1996-01-11",
        "nationalite": "Suisse",
        "numero": 6,
        "taille": 182,
        "poids": 78
      },
      {
        "id": 95694,
        "nom": "Adrien Rabiot",
        "position": "Milieu",
        "position_id": 26,
        "age": "1995-04-03",
        "nationalite": "France",
        "numero": 25,
        "taille": 191,
        "poids": 71
      },
      {
        "id": 96691,
        "nom": "Amine Harit",
        "position": "Milieu",
        "position_id": 26,
        "age": "1997-06-18",
        "nationalite": "Maroc",
        "numero": 11,
        "taille": 180,
        "poids": 67
      },
      {
        "id": 608285,
        "nom": "Angel Gomes",
        "position": "Milieu",
        "position_id": 26,
        "age": "2000-08-31",
        "nationalite": "Angleterre",
        "numero": 8,
        "taille": 168,
        "poids": 61
      },
      {
        "id": 21803033,
        "nom": "Azzedine Ounahi",
        "position": "Milieu",
        "position_id": 26,
        "age": "2000-04-19",
        "nationalite": "Maroc",
        "numero": null,
        "taille": 182,
        "poids": null
      },
      {
        "id": 37541144,
        "nom": "Bilal Nadir",
        "position": "Milieu",
        "position_id": 26,
        "age": "2003-11-28",
        "nationalite": "France",
        "numero": 26,
        "taille": 179,
        "poids": null
      },
      {
        "id": 37737405,
        "nom": "Darryl Bakola",
        "position": "Milieu",
        "position_id": 26,
        "age": "2007-11-30",
        "nationalite": "Inconnue",
        "numero": 50,
        "taille": 178,
        "poids": null
      },
      {
        "id": 95696,
        "nom": "Geoffrey Kondogbia",
        "position": "Milieu",
        "position_id": 26,
        "age": "1993-02-15",
        "nationalite": "République centrafricaine",
        "numero": 19,
        "taille": 188,
        "poids": 80
      },
      {
        "id": 1744,
        "nom": "Pierre-Emile Højbjerg",
        "position": "Milieu",
        "position_id": 26,
        "age": "1995-08-05",
        "nationalite": "Danemark",
        "numero": 23,
        "taille": 185,
        "poids": 84
      },
      {
        "id": 433458,
        "nom": "Amine Gouiri",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2000-02-16",
        "nationalite": "Algérie",
        "numero": 9,
        "taille": 181,
        "poids": 72
      },
      {
        "id": 20315925,
        "nom": "Faris Moumbagna",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2000-07-01",
        "nationalite": "Cameroun",
        "numero": null,
        "taille": 185,
        "poids": 77
      },
      {
        "id": 37657133,
        "nom": "François Mughe",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2004-06-16",
        "nationalite": "Cameroun",
        "numero": 24,
        "taille": 173,
        "poids": null
      },
      {
        "id": 29328428,
        "nom": "Igor Paixão ",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2000-06-28",
        "nationalite": "Brésil",
        "numero": 14,
        "taille": 168,
        "poids": null
      },
      {
        "id": 34455209,
        "nom": "Jonathan Rowe",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2003-04-30",
        "nationalite": "Angleterre",
        "numero": 17,
        "taille": 173,
        "poids": null
      },
      {
        "id": 20333643,
        "nom": "Mason Greenwood",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2001-10-01",
        "nationalite": "Angleterre",
        "numero": 10,
        "taille": 181,
        "poids": null
      },
      {
        "id": 95776,
        "nom": "Neal Maupay",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1996-08-14",
        "nationalite": "France",
        "numero": 7,
        "taille": 171,
        "poids": 69
      },
      {
        "id": 31739,
        "nom": "Pierre-Emerick Aubameyang",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1989-06-18",
        "nationalite": "Gabon",
        "numero": 97,
        "taille": 187,
        "poids": 80
      },
      {
        "id": 537332,
        "nom": "Timothy Weah",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2000-02-22",
        "nationalite": "États-Unis",
        "numero": 22,
        "taille": 183,
        "poids": 66
      }
    ]
  },
  "lyon": {
    "club_id": 79,
    "club_name": "Olympique Lyonnais",
    "players": [
      {
        "id": 37665354,
        "nom": "Lassine Diarra",
        "position": "Gardien",
        "position_id": 24,
        "age": "2002-11-11",
        "nationalite": "Mali",
        "numero": 50,
        "taille": 190,
        "poids": null
      },
      {
        "id": 37337155,
        "nom": "Mathieu Patouillet",
        "position": "Gardien",
        "position_id": 24,
        "age": "2004-02-20",
        "nationalite": "France",
        "numero": null,
        "taille": 188,
        "poids": null
      },
      {
        "id": 97438,
        "nom": "Rémy Descamps",
        "position": "Gardien",
        "position_id": 24,
        "age": "1996-06-25",
        "nationalite": "France",
        "numero": 40,
        "taille": 196,
        "poids": 74
      },
      {
        "id": 29313248,
        "nom": "Abner",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2000-05-27",
        "nationalite": "Brésil",
        "numero": 16,
        "taille": 181,
        "poids": null
      },
      {
        "id": 37634183,
        "nom": "Achraf Laâziri",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2003-07-08",
        "nationalite": "Maroc",
        "numero": null,
        "taille": 177,
        "poids": null
      },
      {
        "id": 4344,
        "nom": "Ainsley Maitland-Niles",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1997-08-29",
        "nationalite": "Angleterre",
        "numero": 98,
        "taille": 180,
        "poids": 71
      },
      {
        "id": 62374,
        "nom": "Clinton Mata",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1992-11-07",
        "nationalite": "Angola",
        "numero": 22,
        "taille": 180,
        "poids": 72
      },
      {
        "id": 98874,
        "nom": "Moussa Niakhaté",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1996-03-08",
        "nationalite": "Sénégal",
        "numero": 19,
        "taille": 190,
        "poids": 80
      },
      {
        "id": 188444,
        "nom": "Nicolás Tagliafico",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1992-08-31",
        "nationalite": "Argentine",
        "numero": 3,
        "taille": 171,
        "poids": 65
      },
      {
        "id": 37395347,
        "nom": "Ruben Kluivert",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2001-05-21",
        "nationalite": "Pays-Bas",
        "numero": 21,
        "taille": 187,
        "poids": null
      },
      {
        "id": 37591826,
        "nom": "Saël Kumbedi",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2005-03-26",
        "nationalite": "France",
        "numero": 20,
        "taille": 175,
        "poids": null
      },
      {
        "id": 37332629,
        "nom": "Adam Karabec",
        "position": "Milieu",
        "position_id": 26,
        "age": "2003-07-02",
        "nationalite": "République tchèque",
        "numero": 7,
        "taille": 187,
        "poids": null
      },
      {
        "id": 96122,
        "nom": "Corentin Tolisso",
        "position": "Milieu",
        "position_id": 26,
        "age": "1994-08-03",
        "nationalite": "France",
        "numero": 8,
        "taille": 181,
        "poids": 81
      },
      {
        "id": 37618903,
        "nom": "Islamdine Halifa",
        "position": "Milieu",
        "position_id": 26,
        "age": "2004-12-20",
        "nationalite": "France",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 37933263,
        "nom": "Khalis Merah",
        "position": "Milieu",
        "position_id": 26,
        "age": "2007-02-24",
        "nationalite": "Inconnue",
        "numero": 44,
        "taille": null,
        "poids": null
      },
      {
        "id": 37611856,
        "nom": "Mahamadou Diawara",
        "position": "Milieu",
        "position_id": 26,
        "age": "2005-02-17",
        "nationalite": "France",
        "numero": null,
        "taille": 187,
        "poids": null
      },
      {
        "id": 523939,
        "nom": "Orel Mangala ",
        "position": "Milieu",
        "position_id": 26,
        "age": "1998-03-18",
        "nationalite": "Belgique",
        "numero": 5,
        "taille": 178,
        "poids": 78
      },
      {
        "id": 93900,
        "nom": "Paul Akouokou",
        "position": "Milieu",
        "position_id": 26,
        "age": "1997-12-20",
        "nationalite": "Côte d'Ivoire",
        "numero": 4,
        "taille": 181,
        "poids": null
      },
      {
        "id": 24469162,
        "nom": "Pavel Sulc",
        "position": "Milieu",
        "position_id": 26,
        "age": "2000-12-29",
        "nationalite": "République tchèque",
        "numero": 10,
        "taille": 177,
        "poids": 70
      },
      {
        "id": 27081112,
        "nom": "Tanner Tessmann",
        "position": "Milieu",
        "position_id": 26,
        "age": "2001-09-24",
        "nationalite": "États-Unis",
        "numero": 6,
        "taille": 188,
        "poids": 86
      },
      {
        "id": 37316836,
        "nom": "Tyler Morton",
        "position": "Milieu",
        "position_id": 26,
        "age": "2002-10-31",
        "nationalite": "Angleterre",
        "numero": 23,
        "taille": 185,
        "poids": null
      },
      {
        "id": 37597737,
        "nom": "Afonso Moreira",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2005-03-19",
        "nationalite": "Portugal",
        "numero": 17,
        "taille": 176,
        "poids": null
      },
      {
        "id": 37681302,
        "nom": "Alejandro Gomes Rodríguez",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2008-03-11",
        "nationalite": "Angleterre",
        "numero": 32,
        "taille": 176,
        "poids": null
      },
      {
        "id": 37756945,
        "nom": "Enzo Molebe",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2007-09-18",
        "nationalite": "Inconnue",
        "numero": 29,
        "taille": null,
        "poids": null
      },
      {
        "id": 37614052,
        "nom": "Ernest Nuamah ",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2003-11-01",
        "nationalite": "Ghana",
        "numero": 37,
        "taille": 178,
        "poids": null
      },
      {
        "id": 13963088,
        "nom": "Georges Mikautadze",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2000-10-31",
        "nationalite": "Georgia",
        "numero": 69,
        "taille": 176,
        "poids": null
      },
      {
        "id": 37590635,
        "nom": "Malick Fofana",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2005-03-31",
        "nationalite": "Belgique",
        "numero": 11,
        "taille": 169,
        "poids": null
      }
    ]
  },
  "monaco": {
    "club_id": 6789,
    "club_name": "AS Monaco",
    "players": [
      {
        "id": 1030177,
        "nom": "Philipp Köhn",
        "position": "Gardien",
        "position_id": 24,
        "age": "1998-04-02",
        "nationalite": "Suisse",
        "numero": 16,
        "taille": 190,
        "poids": 80
      },
      {
        "id": 37532178,
        "nom": "Yann Lienard",
        "position": "Gardien",
        "position_id": 24,
        "age": "2003-03-16",
        "nationalite": "France",
        "numero": 50,
        "taille": 194,
        "poids": null
      },
      {
        "id": 187557,
        "nom": "Caio Henrique",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1997-07-31",
        "nationalite": "Brésil",
        "numero": 12,
        "taille": 178,
        "poids": 69
      },
      {
        "id": 37631969,
        "nom": "Christian Mawissa",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2005-04-18",
        "nationalite": "France",
        "numero": 13,
        "taille": 184,
        "poids": null
      },
      {
        "id": 916,
        "nom": "Eric Dier",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1994-01-15",
        "nationalite": "Angleterre",
        "numero": 3,
        "taille": 191,
        "poids": 88
      },
      {
        "id": 537422,
        "nom": "Jordan Teze",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1999-09-30",
        "nationalite": "Pays-Bas",
        "numero": 4,
        "taille": 183,
        "poids": 68
      },
      {
        "id": 37590868,
        "nom": "Kassoum Ouattara",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2004-10-14",
        "nationalite": "France",
        "numero": 20,
        "taille": 176,
        "poids": null
      },
      {
        "id": 11347016,
        "nom": "Mohammed Salisu",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1999-04-17",
        "nationalite": "Ghana",
        "numero": 22,
        "taille": 188,
        "poids": 82
      },
      {
        "id": 32738,
        "nom": "Thilo Kehrer",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1996-09-21",
        "nationalite": "Allemagne",
        "numero": 5,
        "taille": 186,
        "poids": 76
      },
      {
        "id": 37547795,
        "nom": "Vanderson",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2001-06-21",
        "nationalite": "Brésil",
        "numero": 2,
        "taille": 173,
        "poids": null
      },
      {
        "id": 31640130,
        "nom": "Wilfried Singo",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2000-12-25",
        "nationalite": "Côte d'Ivoire",
        "numero": 17,
        "taille": 190,
        "poids": null
      },
      {
        "id": 170199,
        "nom": "Aleksandr Golovin",
        "position": "Milieu",
        "position_id": 26,
        "age": "1996-05-30",
        "nationalite": "Russie",
        "numero": 10,
        "taille": 178,
        "poids": 69
      },
      {
        "id": 198051,
        "nom": "Denis Zakaria ",
        "position": "Milieu",
        "position_id": 26,
        "age": "1996-11-20",
        "nationalite": "Suisse",
        "numero": 6,
        "taille": 190,
        "poids": 80
      },
      {
        "id": 37642676,
        "nom": "Lamine Camara",
        "position": "Milieu",
        "position_id": 26,
        "age": "2004-01-01",
        "nationalite": "Sénégal",
        "numero": 15,
        "taille": 173,
        "poids": null
      },
      {
        "id": 1992,
        "nom": "Paul Pogba",
        "position": "Milieu",
        "position_id": 26,
        "age": "1993-03-15",
        "nationalite": "France",
        "numero": 8,
        "taille": 191,
        "poids": 84
      },
      {
        "id": 37585962,
        "nom": "Soungoutou Magassa",
        "position": "Milieu",
        "position_id": 26,
        "age": "2003-10-08",
        "nationalite": "France",
        "numero": 88,
        "taille": 190,
        "poids": null
      },
      {
        "id": 23269740,
        "nom": "Ansu Fati",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2002-10-31",
        "nationalite": "Espagne",
        "numero": 31,
        "taille": 178,
        "poids": null
      },
      {
        "id": 32538,
        "nom": "Breel Embolo",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1997-02-14",
        "nationalite": "Suisse",
        "numero": 36,
        "taille": 187,
        "poids": 86
      },
      {
        "id": 37601342,
        "nom": "Eliesse Ben Seghir",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2005-02-16",
        "nationalite": "Maroc",
        "numero": 7,
        "taille": 178,
        "poids": null
      },
      {
        "id": 4969702,
        "nom": "Folarin Balogun",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2001-07-03",
        "nationalite": "Angleterre",
        "numero": 9,
        "taille": 178,
        "poids": null
      },
      {
        "id": 37667455,
        "nom": "George Ilenikhena",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2006-08-16",
        "nationalite": "France",
        "numero": 21,
        "taille": 185,
        "poids": null
      },
      {
        "id": 430403,
        "nom": "Krépin Diatta",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1999-02-25",
        "nationalite": "Sénégal",
        "numero": 27,
        "taille": 175,
        "poids": 68
      },
      {
        "id": 37601345,
        "nom": "Lucas Michal",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2005-06-22",
        "nationalite": "France",
        "numero": 41,
        "taille": null,
        "poids": null
      },
      {
        "id": 37530901,
        "nom": "Maghnes Akliouche",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2002-02-25",
        "nationalite": "France",
        "numero": 11,
        "taille": 183,
        "poids": null
      },
      {
        "id": 28912753,
        "nom": "Mika Biereth",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2003-02-08",
        "nationalite": "Danemark",
        "numero": 14,
        "taille": 187,
        "poids": null
      },
      {
        "id": 29323,
        "nom": "Myron Boadu",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2001-01-14",
        "nationalite": "Pays-Bas",
        "numero": null,
        "taille": 181,
        "poids": 67
      },
      {
        "id": 37650068,
        "nom": "Paris Brunner",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2006-02-15",
        "nationalite": "Allemagne",
        "numero": null,
        "taille": 186,
        "poids": null
      },
      {
        "id": 52671,
        "nom": "Takumi Minamino",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1995-01-16",
        "nationalite": "Japon",
        "numero": 18,
        "taille": 172,
        "poids": 68
      },
      {
        "id": 32539,
        "nom": "Lukas Hradecky ",
        "position": "Inconnu",
        "position_id": null,
        "age": "1989-11-24",
        "nationalite": "Finlande",
        "numero": null,
        "taille": 192,
        "poids": 85
      }
    ]
  },
  "lille": {
    "club_id": 65,
    "club_name": "Lille OSC",
    "players": [
      {
        "id": 1131,
        "nom": "Alex McCarthy",
        "position": "Gardien",
        "position_id": 24,
        "age": "1989-12-03",
        "nationalite": "Angleterre",
        "numero": 1,
        "taille": 193,
        "poids": 79
      },
      {
        "id": 16845996,
        "nom": "Gavin Bazunu ",
        "position": "Gardien",
        "position_id": 24,
        "age": "2002-02-20",
        "nationalite": "République d'Irlande",
        "numero": 31,
        "taille": 188,
        "poids": 79
      },
      {
        "id": 27066567,
        "nom": "Armel Bella-Kotchap",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2001-12-11",
        "nationalite": "Allemagne",
        "numero": 37,
        "taille": 190,
        "poids": null
      },
      {
        "id": 3300,
        "nom": "Charlie Taylor",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1993-09-18",
        "nationalite": "Angleterre",
        "numero": 21,
        "taille": 183,
        "poids": 70
      },
      {
        "id": 1393,
        "nom": "Jack Stephens ",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1994-01-27",
        "nationalite": "Angleterre",
        "numero": 5,
        "taille": 185,
        "poids": 75
      },
      {
        "id": 6513,
        "nom": "James Bree",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1997-12-11",
        "nationalite": "Angleterre",
        "numero": 14,
        "taille": 178,
        "poids": 74
      },
      {
        "id": 37668614,
        "nom": "Joachim Kayi Sanda",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2006-11-29",
        "nationalite": "France",
        "numero": 39,
        "taille": 186,
        "poids": null
      },
      {
        "id": 37588370,
        "nom": "Joshua Quarshie",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2004-07-26",
        "nationalite": "Allemagne",
        "numero": 17,
        "taille": 196,
        "poids": null
      },
      {
        "id": 3188067,
        "nom": "Nathan Wood",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2002-05-31",
        "nationalite": "Angleterre",
        "numero": 15,
        "taille": 188,
        "poids": null
      },
      {
        "id": 37350031,
        "nom": "Ronnie Edwards",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2003-03-28",
        "nationalite": "Angleterre",
        "numero": 12,
        "taille": 185,
        "poids": null
      },
      {
        "id": 7640,
        "nom": "Ryan Manning",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1996-06-14",
        "nationalite": "République d'Irlande",
        "numero": 3,
        "taille": 173,
        "poids": null
      },
      {
        "id": 23278675,
        "nom": "Taylor Harwood-Bellis",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2002-01-30",
        "nationalite": "Angleterre",
        "numero": 6,
        "taille": 188,
        "poids": null
      },
      {
        "id": 37451258,
        "nom": "Welington",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2001-02-19",
        "nationalite": "Brésil",
        "numero": 34,
        "taille": 170,
        "poids": null
      },
      {
        "id": 5666480,
        "nom": "Yukinari Sugawara",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2000-06-28",
        "nationalite": "Japon",
        "numero": 16,
        "taille": 179,
        "poids": 67
      },
      {
        "id": 518749,
        "nom": "Flynn Downes",
        "position": "Milieu",
        "position_id": 26,
        "age": "1999-01-20",
        "nationalite": "Angleterre",
        "numero": 4,
        "taille": 178,
        "poids": null
      },
      {
        "id": 9826,
        "nom": "Joe Aribo",
        "position": "Milieu",
        "position_id": 26,
        "age": "1996-07-21",
        "nationalite": "Nigéria",
        "numero": 7,
        "taille": 183,
        "poids": 76
      },
      {
        "id": 37616360,
        "nom": "Kuryu Matsuki",
        "position": "Milieu",
        "position_id": 26,
        "age": "2003-04-30",
        "nationalite": "Japon",
        "numero": 27,
        "taille": 180,
        "poids": null
      },
      {
        "id": 37593153,
        "nom": "Mateus Fernandes",
        "position": "Milieu",
        "position_id": 26,
        "age": "2004-07-10",
        "nationalite": "Portugal",
        "numero": 18,
        "taille": 178,
        "poids": null
      },
      {
        "id": 37442672,
        "nom": "Shea Charles",
        "position": "Milieu",
        "position_id": 26,
        "age": "2003-11-05",
        "nationalite": "Angleterre",
        "numero": 24,
        "taille": 189,
        "poids": null
      },
      {
        "id": 581052,
        "nom": "Will Smallbone",
        "position": "Milieu",
        "position_id": 26,
        "age": "2000-02-21",
        "nationalite": "République d'Irlande",
        "numero": 8,
        "taille": 183,
        "poids": null
      },
      {
        "id": 2951,
        "nom": "Adam Armstrong",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1997-02-10",
        "nationalite": "Angleterre",
        "numero": 9,
        "taille": 173,
        "poids": 69
      },
      {
        "id": 7835,
        "nom": "Ben Brereton Díaz",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1999-04-18",
        "nationalite": "Chili",
        "numero": 22,
        "taille": 185,
        "poids": null
      },
      {
        "id": 28912777,
        "nom": "Cameron Archer",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2001-12-09",
        "nationalite": "Angleterre",
        "numero": 19,
        "taille": 175,
        "poids": null
      },
      {
        "id": 37592316,
        "nom": "Damion Downs",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2004-07-06",
        "nationalite": "Allemagne",
        "numero": 42,
        "taille": 192,
        "poids": null
      },
      {
        "id": 37617684,
        "nom": "Jay Robinson",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2007-03-15",
        "nationalite": "Angleterre",
        "numero": 46,
        "taille": null,
        "poids": null
      },
      {
        "id": 175530,
        "nom": "Ross Stewart",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1996-07-11",
        "nationalite": "Écosse",
        "numero": 11,
        "taille": 188,
        "poids": 85
      },
      {
        "id": 2712,
        "nom": "Ryan Fraser",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1994-02-24",
        "nationalite": "Écosse",
        "numero": 26,
        "taille": 163,
        "poids": 70
      },
      {
        "id": 37316841,
        "nom": "Samuel Edozie",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2003-01-28",
        "nationalite": "Angleterre",
        "numero": 23,
        "taille": 181,
        "poids": null
      },
      {
        "id": 37561126,
        "nom": "Tyler Dibling",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2006-02-17",
        "nationalite": "Angleterre",
        "numero": 33,
        "taille": 178,
        "poids": null
      }
    ]
  },
  "nice": {
    "club_id": 85,
    "club_name": "OGC Nice",
    "players": [
      {
        "id": 540162,
        "nom": "Dominik Kotarski",
        "position": "Gardien",
        "position_id": 24,
        "age": "2000-02-10",
        "nationalite": "Croatie",
        "numero": 42,
        "taille": 189,
        "poids": null
      },
      {
        "id": 37652786,
        "nom": "Oscar Buur",
        "position": "Gardien",
        "position_id": 24,
        "age": "2006-10-29",
        "nationalite": "Danemark",
        "numero": 61,
        "taille": 180,
        "poids": null
      },
      {
        "id": 84224,
        "nom": "Rúnar Alex Rúnarsson",
        "position": "Gardien",
        "position_id": 24,
        "age": "1995-02-18",
        "nationalite": "Islande",
        "numero": 31,
        "taille": 186,
        "poids": 76
      },
      {
        "id": 151415,
        "nom": "Birger Meling",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1994-12-17",
        "nationalite": "Norvège",
        "numero": 24,
        "taille": 173,
        "poids": 64
      },
      {
        "id": 37295961,
        "nom": "Gabriel Pereira",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2000-05-07",
        "nationalite": "Brésil",
        "numero": 5,
        "taille": 188,
        "poids": null
      },
      {
        "id": 37616318,
        "nom": "Junnosuke Suzuki ",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2003-07-12",
        "nationalite": "Japon",
        "numero": 20,
        "taille": 180,
        "poids": null
      },
      {
        "id": 259454,
        "nom": "Marcos López",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1999-11-20",
        "nationalite": "Pérou",
        "numero": 15,
        "taille": 176,
        "poids": 67
      },
      {
        "id": 37619474,
        "nom": "Munashe Garananga",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2001-01-18",
        "nationalite": "Zimbabwe",
        "numero": 4,
        "taille": 186,
        "poids": null
      },
      {
        "id": 26719,
        "nom": "Pantelis Hatzidiakos",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1997-01-18",
        "nationalite": "Grèce",
        "numero": 6,
        "taille": 185,
        "poids": 75
      },
      {
        "id": 37565765,
        "nom": "Rodrigo Huescas",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2003-09-18",
        "nationalite": "Mexique",
        "numero": 13,
        "taille": 172,
        "poids": null
      },
      {
        "id": 37656059,
        "nom": "Yoram Zague",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2006-05-15",
        "nationalite": "France",
        "numero": 22,
        "taille": 168,
        "poids": null
      },
      {
        "id": 37721101,
        "nom": "Dominik Sarapata",
        "position": "Milieu",
        "position_id": 26,
        "age": "2007-10-25",
        "nationalite": "Pologne",
        "numero": 23,
        "taille": 180,
        "poids": null
      },
      {
        "id": 37652797,
        "nom": "Jonathan Moalem",
        "position": "Milieu",
        "position_id": 26,
        "age": "2007-02-01",
        "nationalite": "Danemark",
        "numero": 29,
        "taille": null,
        "poids": null
      },
      {
        "id": 62898,
        "nom": "Lukas Lerager",
        "position": "Milieu",
        "position_id": 26,
        "age": "1993-07-12",
        "nationalite": "Danemark",
        "numero": 12,
        "taille": 188,
        "poids": 80
      },
      {
        "id": 3533801,
        "nom": "Magnus Mattsson",
        "position": "Milieu",
        "position_id": 26,
        "age": "1999-02-25",
        "nationalite": "Danemark",
        "numero": 8,
        "taille": 174,
        "poids": 62
      },
      {
        "id": 37657040,
        "nom": "Oliver Højer ",
        "position": "Milieu",
        "position_id": 26,
        "age": "2007-01-24",
        "nationalite": "Danemark",
        "numero": 38,
        "taille": 178,
        "poids": null
      },
      {
        "id": 33677,
        "nom": "Thomas Delaney",
        "position": "Milieu",
        "position_id": 26,
        "age": "1991-09-03",
        "nationalite": "Danemark",
        "numero": 27,
        "taille": 182,
        "poids": 71
      },
      {
        "id": 37609216,
        "nom": "William Clem",
        "position": "Milieu",
        "position_id": 26,
        "age": "2004-06-20",
        "nationalite": "Danemark",
        "numero": 36,
        "taille": 191,
        "poids": null
      },
      {
        "id": 4088,
        "nom": "Andreas Cornelius",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1993-03-16",
        "nationalite": "Danemark",
        "numero": 14,
        "taille": 193,
        "poids": 89
      },
      {
        "id": 21413511,
        "nom": "Elias Achouri",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1999-02-10",
        "nationalite": "Tunisie",
        "numero": 30,
        "taille": 177,
        "poids": 68
      },
      {
        "id": 4192333,
        "nom": "German Onugkha ",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1996-07-06",
        "nationalite": "Russie",
        "numero": null,
        "taille": 193,
        "poids": 85
      },
      {
        "id": 26867,
        "nom": "Jordan Larsson",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1997-06-20",
        "nationalite": "Suède",
        "numero": 11,
        "taille": 175,
        "poids": 69
      },
      {
        "id": 37692791,
        "nom": "Liam West",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2007-12-16",
        "nationalite": "Norvège",
        "numero": 49,
        "taille": null,
        "poids": null
      },
      {
        "id": 150759,
        "nom": "Mohamed Elyounoussi",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1994-08-04",
        "nationalite": "Norvège",
        "numero": 10,
        "taille": 178,
        "poids": 70
      },
      {
        "id": 37700158,
        "nom": "Robert",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2005-04-13",
        "nationalite": "Brésil",
        "numero": 16,
        "taille": 174,
        "poids": null
      },
      {
        "id": 172250,
        "nom": "Viktor Claesson ",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1992-01-02",
        "nationalite": "Suède",
        "numero": 7,
        "taille": 183,
        "poids": 75
      },
      {
        "id": 37266015,
        "nom": "Youssoufa Moukoko",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2004-11-20",
        "nationalite": "Allemagne",
        "numero": 9,
        "taille": 179,
        "poids": null
      }
    ]
  },
  "rennes": {
    "club_id": 1163,
    "club_name": "Stade Rennais",
    "players": [
      {
        "id": 37724148,
        "nom": "George Scaife",
        "position": "Gardien",
        "position_id": 24,
        "age": null,
        "nationalite": "Angleterre",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 37536530,
        "nom": "Nick Cranston",
        "position": "Gardien",
        "position_id": 24,
        "age": "2002-06-26",
        "nationalite": "Angleterre",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 7714784,
        "nom": "Shane Bland",
        "position": "Gardien",
        "position_id": 24,
        "age": "1994-09-28",
        "nationalite": "Angleterre",
        "numero": null,
        "taille": 186,
        "poids": null
      },
      {
        "id": 37724150,
        "nom": "Harrison Beeden",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2003-05-08",
        "nationalite": "Angleterre",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 3509965,
        "nom": "Lewis Ritson",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1998-11-01",
        "nationalite": "Angleterre",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 28912788,
        "nom": "Sam Collins",
        "position": "Défenseur",
        "position_id": 25,
        "age": null,
        "nationalite": "Angleterre",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 3877075,
        "nom": "Aaron Haswell",
        "position": "Milieu",
        "position_id": 26,
        "age": "2000-08-16",
        "nationalite": "Angleterre",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 37336453,
        "nom": "Adam Gell",
        "position": "Milieu",
        "position_id": 26,
        "age": null,
        "nationalite": "Angleterre",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 37536811,
        "nom": "Alfie Doherty",
        "position": "Milieu",
        "position_id": 26,
        "age": null,
        "nationalite": "Angleterre",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 37724154,
        "nom": "Jos Storr",
        "position": "Milieu",
        "position_id": 26,
        "age": null,
        "nationalite": "Angleterre",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 537477,
        "nom": "Josef Wheatley",
        "position": "Milieu",
        "position_id": 26,
        "age": "1996-12-30",
        "nationalite": "Angleterre",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 9150,
        "nom": "Lewis Hawkins",
        "position": "Milieu",
        "position_id": 26,
        "age": "1993-06-15",
        "nationalite": "Angleterre",
        "numero": null,
        "taille": 180,
        "poids": 80
      },
      {
        "id": 12790034,
        "nom": "Priestley Griffiths",
        "position": "Milieu",
        "position_id": 26,
        "age": "1996-06-11",
        "nationalite": "Angleterre",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 37724152,
        "nom": "Sam Spenceley",
        "position": "Milieu",
        "position_id": 26,
        "age": null,
        "nationalite": "Angleterre",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 37596997,
        "nom": "Soni Fergus",
        "position": "Milieu",
        "position_id": 26,
        "age": "2001-02-07",
        "nationalite": "Angleterre",
        "numero": null,
        "taille": null,
        "poids": null
      }
    ]
  },
  "lens": {
    "club_id": 66,
    "club_name": "RC Lens",
    "players": [
      {
        "id": 6590,
        "nom": "Jordan Smith",
        "position": "Gardien",
        "position_id": 24,
        "age": "1994-12-08",
        "nationalite": "Angleterre",
        "numero": 13,
        "taille": 183,
        "poids": null
      },
      {
        "id": 37580321,
        "nom": "Murray Johnson",
        "position": "Gardien",
        "position_id": 24,
        "age": "2004-11-13",
        "nationalite": "Écosse",
        "numero": 31,
        "taille": 191,
        "poids": null
      },
      {
        "id": 35708,
        "nom": "Raphael Sallinger",
        "position": "Gardien",
        "position_id": 24,
        "age": "1995-12-08",
        "nationalite": "Autriche",
        "numero": 1,
        "taille": 196,
        "poids": 85
      },
      {
        "id": 172828,
        "nom": "Chris Cadden",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1996-09-19",
        "nationalite": "Écosse",
        "numero": 12,
        "taille": 183,
        "poids": 76
      },
      {
        "id": 807,
        "nom": "Grant Hanley",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1991-11-20",
        "nationalite": "Écosse",
        "numero": null,
        "taille": 188,
        "poids": 81
      },
      {
        "id": 2483202,
        "nom": "Jack Iredale",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1996-05-02",
        "nationalite": "Australie",
        "numero": 15,
        "taille": 184,
        "poids": null
      },
      {
        "id": 2452,
        "nom": "Jordan Obita",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1993-12-08",
        "nationalite": "Angleterre",
        "numero": 21,
        "taille": 181,
        "poids": 74
      },
      {
        "id": 37648631,
        "nom": "Kanayo Megwa",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2004-03-05",
        "nationalite": "Angleterre",
        "numero": 27,
        "taille": null,
        "poids": null
      },
      {
        "id": 1452162,
        "nom": "Rocky Bushiri",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1999-11-30",
        "nationalite": "Belgique",
        "numero": 33,
        "taille": 187,
        "poids": null
      },
      {
        "id": 123099,
        "nom": "Warren O'Hora",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1999-04-19",
        "nationalite": "République d'Irlande",
        "numero": 5,
        "taille": 188,
        "poids": null
      },
      {
        "id": 537593,
        "nom": "Alasana Manneh",
        "position": "Milieu",
        "position_id": 26,
        "age": "1998-04-08",
        "nationalite": "Gambia",
        "numero": 8,
        "taille": 176,
        "poids": null
      },
      {
        "id": 7742181,
        "nom": "Dylan Levitt",
        "position": "Milieu",
        "position_id": 26,
        "age": "2000-11-17",
        "nationalite": "Pays de Galles",
        "numero": 6,
        "taille": 180,
        "poids": null
      },
      {
        "id": 37648632,
        "nom": "Jacob MacIntyre",
        "position": "Milieu",
        "position_id": 26,
        "age": "2006-01-29",
        "nationalite": "Écosse",
        "numero": 30,
        "taille": null,
        "poids": null
      },
      {
        "id": 121792,
        "nom": "Jamie McGrath",
        "position": "Milieu",
        "position_id": 26,
        "age": "1996-09-30",
        "nationalite": "République d'Irlande",
        "numero": 17,
        "taille": 175,
        "poids": 70
      },
      {
        "id": 2781,
        "nom": "Joe Newell ",
        "position": "Milieu",
        "position_id": 26,
        "age": "1993-03-15",
        "nationalite": "Angleterre",
        "numero": 11,
        "taille": 180,
        "poids": 79
      },
      {
        "id": 28184653,
        "nom": "Josh Campbell",
        "position": "Milieu",
        "position_id": 26,
        "age": "2000-05-06",
        "nationalite": "Écosse",
        "numero": 32,
        "taille": 182,
        "poids": null
      },
      {
        "id": 35683623,
        "nom": "Josh Mulligan",
        "position": "Milieu",
        "position_id": 26,
        "age": "2002-11-12",
        "nationalite": "Écosse",
        "numero": 20,
        "taille": 175,
        "poids": null
      },
      {
        "id": 37605120,
        "nom": "Miguel Chaiwa",
        "position": "Milieu",
        "position_id": 26,
        "age": "2004-06-07",
        "nationalite": "Zambia",
        "numero": null,
        "taille": 179,
        "poids": null
      },
      {
        "id": 175335,
        "nom": "Nicky Cadden",
        "position": "Milieu",
        "position_id": 26,
        "age": "1996-09-19",
        "nationalite": "Écosse",
        "numero": 19,
        "taille": 178,
        "poids": null
      },
      {
        "id": 37649472,
        "nom": "Rudi Molotnikov",
        "position": "Milieu",
        "position_id": 26,
        "age": "2006-05-23",
        "nationalite": "Écosse",
        "numero": 35,
        "taille": 179,
        "poids": null
      },
      {
        "id": 261,
        "nom": "Junior Hoilett",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1990-06-05",
        "nationalite": "Canada",
        "numero": 23,
        "taille": 174,
        "poids": 70
      },
      {
        "id": 25954296,
        "nom": "Kieron Bowie",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2002-09-21",
        "nationalite": "Écosse",
        "numero": 9,
        "taille": 190,
        "poids": null
      },
      {
        "id": 172795,
        "nom": "Martin Boyle",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1993-04-25",
        "nationalite": "Australie",
        "numero": 10,
        "taille": 172,
        "poids": 53
      },
      {
        "id": 14338021,
        "nom": "Thibault Klidjé",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2001-07-10",
        "nationalite": "Togo",
        "numero": 18,
        "taille": 170,
        "poids": null
      },
      {
        "id": 432857,
        "nom": "Élie Youan",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1999-04-07",
        "nationalite": "France",
        "numero": 7,
        "taille": 183,
        "poids": 70
      }
    ]
  },
  "reims": {
    "club_id": 538,
    "club_name": "Stade de Reims",
    "players": [
      {
        "id": 37266894,
        "nom": "Fernando Tapia",
        "position": "Gardien",
        "position_id": 24,
        "age": "2001-06-17",
        "nationalite": "Mexique",
        "numero": 31,
        "taille": 185,
        "poids": 79
      },
      {
        "id": 253397,
        "nom": "Guillermo Allison",
        "position": "Gardien",
        "position_id": 24,
        "age": "1990-09-25",
        "nationalite": "Mexique",
        "numero": 25,
        "taille": 192,
        "poids": 90
      },
      {
        "id": 253832,
        "nom": "José Hernández",
        "position": "Gardien",
        "position_id": 24,
        "age": "1997-05-01",
        "nationalite": "Mexique",
        "numero": 1,
        "taille": 182,
        "poids": 67
      },
      {
        "id": 37542773,
        "nom": "Luis Villegas",
        "position": "Gardien",
        "position_id": 24,
        "age": "2001-07-07",
        "nationalite": "Mexique",
        "numero": null,
        "taille": 185,
        "poids": 75
      },
      {
        "id": 37999423,
        "nom": "A. Vélez",
        "position": "Défenseur",
        "position_id": 25,
        "age": null,
        "nationalite": "Inconnue",
        "numero": 182,
        "taille": null,
        "poids": null
      },
      {
        "id": 253920,
        "nom": "Carlos Villanueva",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1994-04-07",
        "nationalite": "Mexique",
        "numero": 15,
        "taille": 184,
        "poids": 76
      },
      {
        "id": 37552941,
        "nom": "Fernando Piñuelas",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1998-03-27",
        "nationalite": "Mexique",
        "numero": 30,
        "taille": 182,
        "poids": 70
      },
      {
        "id": 255141,
        "nom": "Francisco Venegas",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1998-07-16",
        "nationalite": "Mexique",
        "numero": 17,
        "taille": 184,
        "poids": 58
      },
      {
        "id": 253548,
        "nom": "Jaime Gómez",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1993-07-17",
        "nationalite": "Mexique",
        "numero": 12,
        "taille": 175,
        "poids": 68
      },
      {
        "id": 37683985,
        "nom": "Juan Robles",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2003-09-18",
        "nationalite": "Mexique",
        "numero": 23,
        "taille": 167,
        "poids": 60
      },
      {
        "id": 253862,
        "nom": "Kevin Escamilla ",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1994-02-21",
        "nationalite": "Mexique",
        "numero": 5,
        "taille": 177,
        "poids": 72
      },
      {
        "id": 253860,
        "nom": "Omar Mendoza",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1988-10-28",
        "nationalite": "Mexique",
        "numero": 2,
        "taille": 173,
        "poids": 71
      },
      {
        "id": 37761154,
        "nom": "Sebastián Hernández",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2004-03-13",
        "nationalite": "Inconnue",
        "numero": 199,
        "taille": 174,
        "poids": 69
      },
      {
        "id": 7690298,
        "nom": "Óscar Manzanárez",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1995-04-24",
        "nationalite": "Mexique",
        "numero": 3,
        "taille": 180,
        "poids": 70
      },
      {
        "id": 37725771,
        "nom": "Aldahir Pérez",
        "position": "Milieu",
        "position_id": 26,
        "age": "2004-10-04",
        "nationalite": "Mexique",
        "numero": 19,
        "taille": 175,
        "poids": null
      },
      {
        "id": 34862164,
        "nom": "Bruce El-mesmari",
        "position": "Milieu",
        "position_id": 26,
        "age": "2002-04-23",
        "nationalite": "Mexique",
        "numero": 7,
        "taille": 167,
        "poids": 57
      },
      {
        "id": 38037217,
        "nom": "C. Figueroa",
        "position": "Milieu",
        "position_id": 26,
        "age": null,
        "nationalite": "Inconnue",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 215795,
        "nom": "Carlos Valenzuela",
        "position": "Milieu",
        "position_id": 26,
        "age": "1997-04-22",
        "nationalite": "Argentine",
        "numero": 32,
        "taille": 165,
        "poids": 69
      },
      {
        "id": 37552871,
        "nom": "Christian Leyva",
        "position": "Milieu",
        "position_id": 26,
        "age": "2003-07-31",
        "nationalite": "Mexique",
        "numero": 15,
        "taille": 168,
        "poids": 65
      },
      {
        "id": 7690297,
        "nom": "Edson Partida",
        "position": "Milieu",
        "position_id": 26,
        "age": "1997-12-13",
        "nationalite": "Mexique",
        "numero": 22,
        "taille": 176,
        "poids": 76
      },
      {
        "id": 30831346,
        "nom": "Eduardo Armenta",
        "position": "Milieu",
        "position_id": 26,
        "age": "2001-12-16",
        "nationalite": "Mexique",
        "numero": 13,
        "taille": 173,
        "poids": 63
      },
      {
        "id": 211772,
        "nom": "Federico Lértora",
        "position": "Milieu",
        "position_id": 26,
        "age": "1990-07-05",
        "nationalite": "Argentine",
        "numero": 14,
        "taille": 185,
        "poids": 73
      },
      {
        "id": 37551162,
        "nom": "Fernando González",
        "position": "Milieu",
        "position_id": 26,
        "age": "2001-04-26",
        "nationalite": "Mexique",
        "numero": 21,
        "taille": 177,
        "poids": 58
      },
      {
        "id": 37717629,
        "nom": "Jesús Arellano Camacho",
        "position": "Milieu",
        "position_id": 26,
        "age": "2004-12-22",
        "nationalite": "Mexique",
        "numero": 201,
        "taille": null,
        "poids": null
      },
      {
        "id": 245098,
        "nom": "Jhojan Julio",
        "position": "Milieu",
        "position_id": 26,
        "age": "1998-02-11",
        "nationalite": "Équateur",
        "numero": 7,
        "taille": 170,
        "poids": null
      },
      {
        "id": 4237112,
        "nom": "Jonathan Perlaza",
        "position": "Milieu",
        "position_id": 26,
        "age": "1997-09-13",
        "nationalite": "Équateur",
        "numero": 26,
        "taille": 175,
        "poids": null
      },
      {
        "id": 333665,
        "nom": "Lucas Rodríguez",
        "position": "Milieu",
        "position_id": 26,
        "age": "1997-04-27",
        "nationalite": "Argentine",
        "numero": 10,
        "taille": 169,
        "poids": 64
      },
      {
        "id": 37570374,
        "nom": "M. Río",
        "position": "Milieu",
        "position_id": 26,
        "age": "2001-03-14",
        "nationalite": "Argentine",
        "numero": 5,
        "taille": 180,
        "poids": 72
      },
      {
        "id": 37571016,
        "nom": "Santiago Damián Homenchenko Bianchi",
        "position": "Milieu",
        "position_id": 26,
        "age": "2003-08-30",
        "nationalite": "Uruguay",
        "numero": 8,
        "taille": 186,
        "poids": 78
      },
      {
        "id": 37528332,
        "nom": "Ángel Zapata",
        "position": "Milieu",
        "position_id": 26,
        "age": "2001-02-03",
        "nationalite": "Mexique",
        "numero": 16,
        "taille": 166,
        "poids": 60
      },
      {
        "id": 2158445,
        "nom": "Alan Medina",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1997-08-19",
        "nationalite": "Mexique",
        "numero": 11,
        "taille": 180,
        "poids": 74
      },
      {
        "id": 37343046,
        "nom": "Alí Ávila",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2003-09-23",
        "nationalite": "Mexique",
        "numero": 31,
        "taille": 178,
        "poids": 65
      },
      {
        "id": 37789958,
        "nom": "Antonio de María y Campos",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2004-04-12",
        "nationalite": "Inconnue",
        "numero": 184,
        "taille": 184,
        "poids": null
      },
      {
        "id": 1873110,
        "nom": "Daniel López",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2000-03-14",
        "nationalite": "Mexique",
        "numero": 27,
        "taille": 180,
        "poids": 67
      },
      {
        "id": 37582896,
        "nom": "Jesús Hernández",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2004-01-09",
        "nationalite": "Mexique",
        "numero": 14,
        "taille": 180,
        "poids": null
      },
      {
        "id": 37261679,
        "nom": "Luis Gutiérrez",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2001-10-17",
        "nationalite": "Mexique",
        "numero": 35,
        "taille": 178,
        "poids": 79
      },
      {
        "id": 344,
        "nom": "Pablo Barrera",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1987-06-21",
        "nationalite": "Mexique",
        "numero": 8,
        "taille": 175,
        "poids": 68
      },
      {
        "id": 257877,
        "nom": "Rodrigo Bogarín",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1997-05-24",
        "nationalite": "Paraguay",
        "numero": 28,
        "taille": 182,
        "poids": 76
      },
      {
        "id": 253745,
        "nom": "Ronaldo Cisneros",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1997-01-08",
        "nationalite": "Mexique",
        "numero": 18,
        "taille": 180,
        "poids": 74
      }
    ]
  },
  "nantes": {
    "club_id": 82,
    "club_name": "FC Nantes",
    "players": [
      {
        "id": 36809,
        "nom": "Markus Kolke",
        "position": "Gardien",
        "position_id": 24,
        "age": "1990-08-18",
        "nationalite": "Allemagne",
        "numero": 25,
        "taille": 187,
        "poids": 91
      },
      {
        "id": 32406,
        "nom": "Michael Zetterer",
        "position": "Gardien",
        "position_id": 24,
        "age": "1995-07-12",
        "nationalite": "Allemagne",
        "numero": 1,
        "taille": 187,
        "poids": 79
      },
      {
        "id": 37558978,
        "nom": "Mio Backhaus",
        "position": "Gardien",
        "position_id": 24,
        "age": "2004-04-16",
        "nationalite": "Allemagne",
        "numero": 30,
        "taille": 194,
        "poids": 70
      },
      {
        "id": 37642893,
        "nom": "Stefan Smarkalev",
        "position": "Gardien",
        "position_id": 24,
        "age": "2007-05-14",
        "nationalite": "Bulgarie",
        "numero": 37,
        "taille": 188,
        "poids": null
      },
      {
        "id": 537599,
        "nom": "Amos Pieper",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1998-01-17",
        "nationalite": "Allemagne",
        "numero": 5,
        "taille": 192,
        "poids": 84
      },
      {
        "id": 3861479,
        "nom": "Felix Agu",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1999-09-27",
        "nationalite": "Allemagne",
        "numero": 27,
        "taille": 180,
        "poids": null
      },
      {
        "id": 37547066,
        "nom": "Julián Malatini",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2001-05-31",
        "nationalite": "Argentine",
        "numero": 22,
        "taille": 191,
        "poids": null
      },
      {
        "id": 37675898,
        "nom": "Karim Coulibaly",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2007-05-23",
        "nationalite": "Allemagne",
        "numero": 31,
        "taille": 191,
        "poids": null
      },
      {
        "id": 33701,
        "nom": "Marco Friedl ",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1998-03-16",
        "nationalite": "Autriche",
        "numero": 32,
        "taille": 187,
        "poids": 71
      },
      {
        "id": 52850,
        "nom": "Maximilian Wöber",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1998-02-04",
        "nationalite": "Autriche",
        "numero": 39,
        "taille": 188,
        "poids": 82
      },
      {
        "id": 37652849,
        "nom": "Mick Schmetgens",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2007-09-09",
        "nationalite": "Allemagne",
        "numero": 33,
        "taille": 190,
        "poids": null
      },
      {
        "id": 31636,
        "nom": "Mitchell Weiser ",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1994-04-21",
        "nationalite": "Allemagne",
        "numero": 8,
        "taille": 177,
        "poids": 71
      },
      {
        "id": 31772,
        "nom": "Niklas Stark",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1995-04-14",
        "nationalite": "Allemagne",
        "numero": 4,
        "taille": 190,
        "poids": 88
      },
      {
        "id": 23660720,
        "nom": "Olivier Deman ",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2000-04-06",
        "nationalite": "Belgique",
        "numero": 2,
        "taille": 181,
        "poids": null
      },
      {
        "id": 37538006,
        "nom": "Dikeni Salifou",
        "position": "Milieu",
        "position_id": 26,
        "age": "2003-06-08",
        "nationalite": "Togo",
        "numero": 40,
        "taille": 191,
        "poids": null
      },
      {
        "id": 37417046,
        "nom": "Isak Hansen-Aarøen",
        "position": "Milieu",
        "position_id": 26,
        "age": "2004-08-22",
        "nationalite": "Norvège",
        "numero": 21,
        "taille": 173,
        "poids": null
      },
      {
        "id": 84658,
        "nom": "Jens Stage ",
        "position": "Milieu",
        "position_id": 26,
        "age": "1996-11-08",
        "nationalite": "Danemark",
        "numero": 6,
        "taille": 187,
        "poids": 83
      },
      {
        "id": 37626733,
        "nom": "Leon Opitz",
        "position": "Milieu",
        "position_id": 26,
        "age": "2005-04-11",
        "nationalite": "Allemagne",
        "numero": 35,
        "taille": 183,
        "poids": null
      },
      {
        "id": 31729,
        "nom": "Leonardo Bittencourt",
        "position": "Milieu",
        "position_id": 26,
        "age": "1993-12-19",
        "nationalite": "Allemagne",
        "numero": 10,
        "taille": 171,
        "poids": 63
      },
      {
        "id": 37695942,
        "nom": "Patrice Covic",
        "position": "Milieu",
        "position_id": 26,
        "age": "2007-06-25",
        "nationalite": "Croatie",
        "numero": 24,
        "taille": null,
        "poids": null
      },
      {
        "id": 459660,
        "nom": "Romano Schmid",
        "position": "Milieu",
        "position_id": 26,
        "age": "2000-01-27",
        "nationalite": "Autriche",
        "numero": 20,
        "taille": 168,
        "poids": 63
      },
      {
        "id": 539990,
        "nom": "Senne Lynen",
        "position": "Milieu",
        "position_id": 26,
        "age": "1999-02-19",
        "nationalite": "Belgique",
        "numero": 14,
        "taille": 185,
        "poids": null
      },
      {
        "id": 37304087,
        "nom": "Skelly Alvero",
        "position": "Milieu",
        "position_id": 26,
        "age": "2002-05-04",
        "nationalite": "France",
        "numero": 28,
        "taille": 202,
        "poids": 85
      },
      {
        "id": 37670222,
        "nom": "Wesley Adeh",
        "position": "Milieu",
        "position_id": 26,
        "age": "2007-01-08",
        "nationalite": "Allemagne",
        "numero": 34,
        "taille": 187,
        "poids": null
      },
      {
        "id": 37259284,
        "nom": "Justin Njinmah ",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2000-11-15",
        "nationalite": "Allemagne",
        "numero": 11,
        "taille": 185,
        "poids": null
      },
      {
        "id": 37588260,
        "nom": "Keke Topp",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2004-03-25",
        "nationalite": "Allemagne",
        "numero": 9,
        "taille": 192,
        "poids": null
      },
      {
        "id": 349061,
        "nom": "Marco Grüll",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1998-07-06",
        "nationalite": "Autriche",
        "numero": 17,
        "taille": 182,
        "poids": 71
      },
      {
        "id": 37650873,
        "nom": "Salim Musah",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2006-02-22",
        "nationalite": "Allemagne",
        "numero": 29,
        "taille": 198,
        "poids": null
      },
      {
        "id": 37459063,
        "nom": "Samuel Mbangula",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2004-01-16",
        "nationalite": "Belgique",
        "numero": null,
        "taille": 179,
        "poids": null
      }
    ]
  },
  "montpellier": {
    "club_id": 71,
    "club_name": "Montpellier HSC",
    "players": [
      {
        "id": 5569,
        "nom": "Alex Cairns",
        "position": "Gardien",
        "position_id": 24,
        "age": "1993-01-04",
        "nationalite": "Angleterre",
        "numero": 21,
        "taille": 183,
        "poids": 72
      },
      {
        "id": 432881,
        "nom": "Illan Meslier",
        "position": "Gardien",
        "position_id": 24,
        "age": "2000-03-02",
        "nationalite": "France",
        "numero": 1,
        "taille": 197,
        "poids": null
      },
      {
        "id": 1397,
        "nom": "Karl Darlow",
        "position": "Gardien",
        "position_id": 24,
        "age": "1990-10-08",
        "nationalite": "Angleterre",
        "numero": 26,
        "taille": 190,
        "poids": 88
      },
      {
        "id": 460159,
        "nom": "Lucas Perri",
        "position": "Gardien",
        "position_id": 24,
        "age": "1997-12-10",
        "nationalite": "Brésil",
        "numero": null,
        "taille": 197,
        "poids": 98
      },
      {
        "id": 12542,
        "nom": "Ethan Ampadu",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2000-09-14",
        "nationalite": "Pays de Galles",
        "numero": 4,
        "taille": 182,
        "poids": 78
      },
      {
        "id": 193196,
        "nom": "Gabriel Gudmundsson",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1999-04-29",
        "nationalite": "Suède",
        "numero": null,
        "taille": 180,
        "poids": 74
      },
      {
        "id": 37522387,
        "nom": "Isaac Schmidt",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1999-12-07",
        "nationalite": "Suisse",
        "numero": 33,
        "taille": 172,
        "poids": null
      },
      {
        "id": 1548632,
        "nom": "Jaka Bijol",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1999-02-05",
        "nationalite": "Slovénie",
        "numero": 15,
        "taille": 190,
        "poids": 79
      },
      {
        "id": 581158,
        "nom": "Jayden Bogle",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2000-07-27",
        "nationalite": "Angleterre",
        "numero": 2,
        "taille": 178,
        "poids": null
      },
      {
        "id": 339112,
        "nom": "Joe Rodon",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1997-10-22",
        "nationalite": "Pays de Galles",
        "numero": 6,
        "taille": 193,
        "poids": 70
      },
      {
        "id": 29478,
        "nom": "Pascal Struijk ",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1999-08-11",
        "nationalite": "Pays-Bas",
        "numero": 5,
        "taille": 190,
        "poids": null
      },
      {
        "id": 1928,
        "nom": "Sam Byram",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1993-09-16",
        "nationalite": "Angleterre",
        "numero": 25,
        "taille": 183,
        "poids": 72
      },
      {
        "id": 4536574,
        "nom": "Sebastiaan Bornauw",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1999-03-22",
        "nationalite": "Belgique",
        "numero": null,
        "taille": 191,
        "poids": 82
      },
      {
        "id": 2178735,
        "nom": "Anton Stach",
        "position": "Milieu",
        "position_id": 26,
        "age": "1998-11-15",
        "nationalite": "Allemagne",
        "numero": null,
        "taille": 194,
        "poids": null
      },
      {
        "id": 461027,
        "nom": "Ao Tanaka",
        "position": "Milieu",
        "position_id": 26,
        "age": "1998-09-10",
        "nationalite": "Japon",
        "numero": 22,
        "taille": 180,
        "poids": 69
      },
      {
        "id": 4552689,
        "nom": "Brenden Aaronson",
        "position": "Milieu",
        "position_id": 26,
        "age": "2000-10-22",
        "nationalite": "États-Unis",
        "numero": 11,
        "taille": 177,
        "poids": 66
      },
      {
        "id": 37604648,
        "nom": "Charlie Crew",
        "position": "Milieu",
        "position_id": 26,
        "age": "2006-06-15",
        "nationalite": "Pays de Galles",
        "numero": 50,
        "taille": 180,
        "poids": null
      },
      {
        "id": 5149,
        "nom": "Daniel James",
        "position": "Milieu",
        "position_id": 26,
        "age": "1997-11-10",
        "nationalite": "Pays de Galles",
        "numero": 7,
        "taille": 171,
        "poids": 76
      },
      {
        "id": 32796077,
        "nom": "Darko Gyabi",
        "position": "Milieu",
        "position_id": 26,
        "age": "2004-02-18",
        "nationalite": "Angleterre",
        "numero": 18,
        "taille": 196,
        "poids": null
      },
      {
        "id": 3861741,
        "nom": "Ilia Gruev",
        "position": "Milieu",
        "position_id": 26,
        "age": "2000-05-06",
        "nationalite": "Bulgarie",
        "numero": 44,
        "taille": 185,
        "poids": null
      },
      {
        "id": 173737,
        "nom": "Sean Longstaff",
        "position": "Milieu",
        "position_id": 26,
        "age": "1997-10-30",
        "nationalite": "Angleterre",
        "numero": null,
        "taille": 187,
        "poids": 65
      },
      {
        "id": 5141,
        "nom": "Dominic Calvert-Lewin",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1997-03-16",
        "nationalite": "Angleterre",
        "numero": null,
        "taille": 189,
        "poids": 71
      },
      {
        "id": 262274,
        "nom": "Jack Harrison",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1996-11-20",
        "nationalite": "Angleterre",
        "numero": null,
        "taille": 175,
        "poids": 70
      },
      {
        "id": 29382,
        "nom": "Joël Piroe",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1999-08-02",
        "nationalite": "Pays-Bas",
        "numero": 10,
        "taille": 185,
        "poids": null
      },
      {
        "id": 13981024,
        "nom": "Largie Ramazani",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2001-02-27",
        "nationalite": "Belgique",
        "numero": 17,
        "taille": 168,
        "poids": null
      },
      {
        "id": 537217,
        "nom": "Lukas Nmecha",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1998-12-14",
        "nationalite": "Allemagne",
        "numero": 14,
        "taille": 185,
        "poids": 80
      },
      {
        "id": 1175,
        "nom": "Patrick Bamford",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1993-09-05",
        "nationalite": "Angleterre",
        "numero": 9,
        "taille": 185,
        "poids": 71
      },
      {
        "id": 28912710,
        "nom": "Sam Greenwood ",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2002-01-26",
        "nationalite": "Angleterre",
        "numero": null,
        "taille": 180,
        "poids": null
      },
      {
        "id": 37316986,
        "nom": "Wilfried Gnonto",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2003-11-05",
        "nationalite": "Italie",
        "numero": 29,
        "taille": 170,
        "poids": null
      }
    ]
  },
  "toulouse": {
    "club_id": 583,
    "club_name": "Toulouse FC",
    "players": [
      {
        "id": 17177617,
        "nom": "Jacob Jackson",
        "position": "Gardien",
        "position_id": 24,
        "age": "2000-04-25",
        "nationalite": "États-Unis",
        "numero": 98,
        "taille": 188,
        "poids": 86
      },
      {
        "id": 26707,
        "nom": "Maarten Paes",
        "position": "Gardien",
        "position_id": 24,
        "age": "1998-05-14",
        "nationalite": "Pays-Bas",
        "numero": 1,
        "taille": 192,
        "poids": 82
      },
      {
        "id": 37917927,
        "nom": "Enzo Newman ",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2005-12-08",
        "nationalite": "Inconnue",
        "numero": 29,
        "taille": 175,
        "poids": null
      },
      {
        "id": 37561659,
        "nom": "Geovane Jesus ",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2001-07-31",
        "nationalite": "Brésil",
        "numero": 2,
        "taille": 181,
        "poids": null
      },
      {
        "id": 37683417,
        "nom": "Herbert Endeley ",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2001-10-09",
        "nationalite": "États-Unis",
        "numero": null,
        "taille": 178,
        "poids": 69
      },
      {
        "id": 37920741,
        "nom": "Joshua Torquato",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2007-07-24",
        "nationalite": "Inconnue",
        "numero": 24,
        "taille": null,
        "poids": null
      },
      {
        "id": 455862,
        "nom": "Lalas Abubakar",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1994-12-25",
        "nationalite": "Ghana",
        "numero": 5,
        "taille": 185,
        "poids": 82
      },
      {
        "id": 37631542,
        "nom": "Malachi Molina",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2006-10-11",
        "nationalite": "Jamaïque",
        "numero": 35,
        "taille": null,
        "poids": null
      },
      {
        "id": 37625954,
        "nom": "Nolan Norris",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2005-02-17",
        "nationalite": "États-Unis",
        "numero": 32,
        "taille": 180,
        "poids": null
      },
      {
        "id": 9308228,
        "nom": "Osaze Urhoghide",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2000-07-04",
        "nationalite": "Angleterre",
        "numero": 3,
        "taille": 188,
        "poids": null
      },
      {
        "id": 85719,
        "nom": "Sebastien Ibeagha",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1992-01-21",
        "nationalite": "États-Unis",
        "numero": 25,
        "taille": 189,
        "poids": 85
      },
      {
        "id": 448320,
        "nom": "Shaq Moore",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1996-11-02",
        "nationalite": "États-Unis",
        "numero": 18,
        "taille": 180,
        "poids": 73
      },
      {
        "id": 37757328,
        "nom": "Álvaro Augusto",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2005-04-17",
        "nationalite": "Inconnue",
        "numero": 22,
        "taille": 193,
        "poids": null
      },
      {
        "id": 37631541,
        "nom": "Alejandro Urzua",
        "position": "Milieu",
        "position_id": 26,
        "age": "2006-04-03",
        "nationalite": "États-Unis",
        "numero": 34,
        "taille": null,
        "poids": null
      },
      {
        "id": 25558182,
        "nom": "Christian Cappis",
        "position": "Milieu",
        "position_id": 26,
        "age": "1999-08-13",
        "nationalite": "États-Unis",
        "numero": 12,
        "taille": 185,
        "poids": 70
      },
      {
        "id": 37585274,
        "nom": "Diego García",
        "position": "Milieu",
        "position_id": 26,
        "age": "2006-10-17",
        "nationalite": "États-Unis",
        "numero": 50,
        "taille": 173,
        "poids": 63
      },
      {
        "id": 37739582,
        "nom": "Kaick",
        "position": "Milieu",
        "position_id": 26,
        "age": "2005-11-29",
        "nationalite": "Inconnue",
        "numero": 55,
        "taille": 175,
        "poids": null
      },
      {
        "id": 37341902,
        "nom": "Patrickson Delgado",
        "position": "Milieu",
        "position_id": 26,
        "age": "2003-10-17",
        "nationalite": "Équateur",
        "numero": 6,
        "taille": 180,
        "poids": 64
      },
      {
        "id": 429921,
        "nom": "Paxton Pomykal ",
        "position": "Milieu",
        "position_id": 26,
        "age": "1999-12-17",
        "nationalite": "États-Unis",
        "numero": 19,
        "taille": 172,
        "poids": 66
      },
      {
        "id": 218639,
        "nom": "Ramiro",
        "position": "Milieu",
        "position_id": 26,
        "age": "1993-05-22",
        "nationalite": "Brésil",
        "numero": 17,
        "taille": 169,
        "poids": 67
      },
      {
        "id": 4282,
        "nom": "Sebastian Lletget",
        "position": "Milieu",
        "position_id": 26,
        "age": "1992-09-03",
        "nationalite": "États-Unis",
        "numero": 8,
        "taille": 178,
        "poids": 75
      },
      {
        "id": 37614793,
        "nom": "Tsiki Ntsabeleng",
        "position": "Milieu",
        "position_id": 26,
        "age": "1998-02-09",
        "nationalite": "Afrique du Sud",
        "numero": 16,
        "taille": 170,
        "poids": null
      },
      {
        "id": 244938,
        "nom": "Anderson Julio",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1996-05-31",
        "nationalite": "Équateur",
        "numero": 11,
        "taille": 171,
        "poids": 70
      },
      {
        "id": 37632274,
        "nom": "Anthony Ramírez",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2005-12-22",
        "nationalite": "États-Unis",
        "numero": 51,
        "taille": 175,
        "poids": null
      },
      {
        "id": 37567969,
        "nom": "Bernard Kamungo",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2002-01-01",
        "nationalite": "Tanzania",
        "numero": 77,
        "taille": 175,
        "poids": 68
      },
      {
        "id": 37748802,
        "nom": "Daniel Baran",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2006-09-16",
        "nationalite": "Inconnue",
        "numero": 36,
        "taille": null,
        "poids": null
      },
      {
        "id": 37588144,
        "nom": "Enes Sali",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2006-02-23",
        "nationalite": "Roumanie",
        "numero": null,
        "taille": 168,
        "poids": null
      },
      {
        "id": 37736885,
        "nom": "Logan Farrington",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2001-12-14",
        "nationalite": "Inconnue",
        "numero": 23,
        "taille": 188,
        "poids": null
      },
      {
        "id": 37259996,
        "nom": "Louicius Deedson",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2001-02-11",
        "nationalite": "Haiti",
        "numero": 7,
        "taille": 178,
        "poids": null
      },
      {
        "id": 37621811,
        "nom": "Pedrinho",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2003-04-18",
        "nationalite": "Brésil",
        "numero": 20,
        "taille": 177,
        "poids": null
      },
      {
        "id": 74250,
        "nom": "Petar Musa",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1998-03-04",
        "nationalite": "Croatie",
        "numero": 9,
        "taille": 188,
        "poids": null
      },
      {
        "id": 37915347,
        "nom": "Sam Sarver",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2003-03-03",
        "nationalite": "Inconnue",
        "numero": 28,
        "taille": 175,
        "poids": null
      },
      {
        "id": 37589446,
        "nom": "Tarik Scott",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2005-04-23",
        "nationalite": "États-Unis",
        "numero": 41,
        "taille": 178,
        "poids": 64
      }
    ]
  },
  "auxerre": {
    "club_id": 1272,
    "club_name": "AJ Auxerre",
    "players": [
      {
        "id": 21772899,
        "nom": "Beau Reus",
        "position": "Gardien",
        "position_id": 24,
        "age": "2001-10-30",
        "nationalite": "Pays-Bas",
        "numero": 1,
        "taille": 198,
        "poids": null
      },
      {
        "id": 37676893,
        "nom": "Josua Lusamba Tshiolola",
        "position": "Gardien",
        "position_id": 24,
        "age": "2004-12-13",
        "nationalite": "DR Congo",
        "numero": 84,
        "taille": null,
        "poids": null
      },
      {
        "id": 34455312,
        "nom": "Maxim De Man",
        "position": "Gardien",
        "position_id": 24,
        "age": "2001-10-23",
        "nationalite": "Belgique",
        "numero": 16,
        "taille": 194,
        "poids": null
      },
      {
        "id": 61734,
        "nom": "Bruno Godeau",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1992-05-10",
        "nationalite": "Belgique",
        "numero": null,
        "taille": 190,
        "poids": 85
      },
      {
        "id": 63907,
        "nom": "Christophe Janssens",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1998-03-09",
        "nationalite": "Belgique",
        "numero": null,
        "taille": 182,
        "poids": 79
      },
      {
        "id": 37555792,
        "nom": "Dylan Dassy",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2003-01-18",
        "nationalite": "Belgique",
        "numero": 20,
        "taille": null,
        "poids": null
      },
      {
        "id": 62718,
        "nom": "Laurent Jans",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1992-08-05",
        "nationalite": "Luxembourg",
        "numero": 21,
        "taille": 178,
        "poids": 73
      },
      {
        "id": 540601,
        "nom": "Viktor Boone",
        "position": "Défenseur",
        "position_id": 25,
        "age": "1998-01-25",
        "nationalite": "Belgique",
        "numero": null,
        "taille": 191,
        "poids": null
      },
      {
        "id": 37643922,
        "nom": "Y. Gomis",
        "position": "Défenseur",
        "position_id": 25,
        "age": "2005-09-23",
        "nationalite": "France",
        "numero": null,
        "taille": 186,
        "poids": null
      },
      {
        "id": 26029,
        "nom": "Christian Brüls",
        "position": "Milieu",
        "position_id": 26,
        "age": "1988-09-30",
        "nationalite": "Belgique",
        "numero": 22,
        "taille": 179,
        "poids": 74
      },
      {
        "id": 65631,
        "nom": "Guillaume De Schryver",
        "position": "Milieu",
        "position_id": 26,
        "age": "1996-11-04",
        "nationalite": "Belgique",
        "numero": 23,
        "taille": 182,
        "poids": null
      },
      {
        "id": 24817170,
        "nom": "Jannes Van Hecke",
        "position": "Milieu",
        "position_id": 26,
        "age": "2002-01-15",
        "nationalite": "Belgique",
        "numero": 78,
        "taille": 177,
        "poids": null
      },
      {
        "id": 37590630,
        "nom": "Noah Emmanuel Mawete Kinsiona",
        "position": "Milieu",
        "position_id": 26,
        "age": "2005-10-17",
        "nationalite": "Belgique",
        "numero": null,
        "taille": 186,
        "poids": null
      },
      {
        "id": 537367,
        "nom": "Sieben Dewaele",
        "position": "Milieu",
        "position_id": 26,
        "age": "1999-02-02",
        "nationalite": "Belgique",
        "numero": 18,
        "taille": 180,
        "poids": null
      },
      {
        "id": 37291445,
        "nom": "Ilyes Najim",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2002-09-10",
        "nationalite": "France",
        "numero": null,
        "taille": 0,
        "poids": null
      },
      {
        "id": 37400489,
        "nom": "Jearl Margaritha",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2000-04-10",
        "nationalite": "Curaçao",
        "numero": null,
        "taille": 181,
        "poids": null
      },
      {
        "id": 64411,
        "nom": "Kurt Abrahams",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1996-12-30",
        "nationalite": "Afrique du Sud",
        "numero": 34,
        "taille": 172,
        "poids": null
      },
      {
        "id": 1481800,
        "nom": "Lennart Mertens",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1992-08-14",
        "nationalite": "Belgique",
        "numero": 92,
        "taille": 188,
        "poids": null
      },
      {
        "id": 37550766,
        "nom": "Mathis Servais",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2004-11-23",
        "nationalite": "Belgique",
        "numero": 8,
        "taille": null,
        "poids": null
      },
      {
        "id": 37623681,
        "nom": "Yutaka Michiwaki",
        "position": "Attaquant",
        "position_id": 27,
        "age": "2006-04-05",
        "nationalite": "Japon",
        "numero": 11,
        "taille": 186,
        "poids": null
      },
      {
        "id": 37710191,
        "nom": "H. Ertürk",
        "position": "Inconnu",
        "position_id": null,
        "age": "2006-03-04",
        "nationalite": "Inconnue",
        "numero": 77,
        "taille": null,
        "poids": null
      }
    ]
  },
  "saint-etienne": {
    "club_id": 1714,
    "club_name": "AS Saint-Etienne",
    "players": [
      {
        "id": 37592708,
        "nom": "Matteo Makhabe",
        "position": "Milieu",
        "position_id": 26,
        "age": "2003-11-28",
        "nationalite": "France",
        "numero": null,
        "taille": 170,
        "poids": null
      },
      {
        "id": 1481791,
        "nom": "Stacy Misiatu Nzumbi",
        "position": "Milieu",
        "position_id": 26,
        "age": "1997-07-17",
        "nationalite": "France",
        "numero": null,
        "taille": null,
        "poids": null
      },
      {
        "id": 98424,
        "nom": "Souleymane Sawadogo",
        "position": "Attaquant",
        "position_id": 27,
        "age": "1993-01-09",
        "nationalite": "Burkina Faso",
        "numero": null,
        "taille": 171,
        "poids": 66
      }
    ]
  }
};
